force-app/main/default/objects/Departments__c/Departments__c.object-meta.xml
<CustomObject>
    <label>Departments</label>
    <nameField>
        <label>Departments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departments__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Departments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tickets__c/Tickets__c.object-meta.xml
<CustomObject>
    <label>Tickets</label>
    <nameField>
        <label>Tickets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tickets__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Non - Existing Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Departments__c.field-meta.xml
<CustomField>
    <fullName>Departments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departments</label>
    <referenceTo>Departments__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Last_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Last_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Ticket</label>
    <referenceTo>Tickets__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Ticket_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Created_Date__c</fullName>
    <label>Ticket Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM Query</fullName>
            </value>
            <value>
                <fullName>Field Query</fullName>
            </value>
            <value>
                <fullName>Billing Query</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Tiling</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Masonry</fullName>
            </value>
            <value>
                <fullName>Doors &amp; windows</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Fabrication (Steel work window grills)</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TicketController.cls
public class TicketController {
    public static void sendTicketEmail(String ticketId, String emailMessage, List<Messaging.EmailFileAttachment> emailAttachments) {
        Tickets__c ticket = [SELECT Id,Customer_Name__c,Departments__c,Project_Name__c,Email__c,Contact_Number__c,Approval_Status__c,Ticket_Type__c,Manager__c,Assigned_To__c,Closed_Date__c,Ticket_Created_Date__c,Comment__c,Last_Ticket__c FROM Tickets__c WHERE Id = :ticketId LIMIT 1];
        
        if (ticket != null && !String.isEmpty(ticket.Email__c)) {
            OrgWideEmailAddress orgWideEmail = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress];

            if (orgWideEmail != null && !String.isEmpty(ticket.Email__c)) {
                system.debug('inside ticket messages controler');
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new List<String>{ticket.Email__c});
                email.setSubject('Ticket Status Update');
                email.setHtmlBody(emailMessage);
                
                email.setUseSignature(false);
                email.setOptOutPolicy('FILTER');
                //email.setSuppressApexCallout(false);
                email.setTreatBodiesAsTemplate(false);
                email.setEmailPriority('Normal');
                
                system.debug('org email'+orgWideEmail.Id);
                email.setOrgWideEmailAddressId(orgWideEmail.Id);
                
                
                email.setFileAttachments(emailAttachments); 
                Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});

            } else {
                System.debug('Org-wide email address not found');
            }
        }
    }
}