force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Balcony_Area__c.field-meta.xml
<CustomField>
    <fullName>Balcony_Area__c</fullName>
    <formula>Plot__r.Balcony_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balcony Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Block1__c.field-meta.xml
<CustomField>
    <fullName>Block1__c</fullName>
    <label>Block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_Charges__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Charges__c</fullName>
    <label>Cancellation Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <formula>IF(
    OR(
        ISPICKVAL(Stage__c, &quot;Reservation&quot;),
        ISPICKVAL(Stage__c, &quot;Agreement&quot;)
    ),
    &quot;Before Agreement Cancellation&quot;,
    IF(
        ISPICKVAL(Stage__c, &quot;Cancellation&quot;),
        &quot;&quot;,
        &quot;After Agreement Cancellation&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cancellation Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cost_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Sheet</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Maintenance_charges__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_charges__c</fullName>
    <label>Maintenance charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Open_Terrace_Area__c.field-meta.xml
<CustomField>
    <fullName>Open_Terrace_Area__c</fullName>
    <formula>Plot__r.Terrace_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open Terrace Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Cost_Sheet__r.Grand_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/Booking_Request__c.object-meta.xml
<CustomObject>
    <label>Booking Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Booking Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Requests</relationshipLabel>
    <relationshipName>Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Unit__r.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Booking Requests</relationshipLabel>
    <relationshipName>Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <description>Payment_percent__c *  Booking__r.Total__c</description>
    <formula>Cost_Sheet__r.Grand_Total__c  * Payment_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received Amount through Receipts</label>
    <summarizedField>Receipt_Line_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Basic_Price__c.field-meta.xml
<CustomField>
    <fullName>Basic_Price__c</fullName>
    <formula>(Final_Price_Per_Sq_ft__c  * Super_Built_Up_Area__c) +((Final_Price_Per_Sq_ft__c/2)* Open_Terrace_Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price for Saleable Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>Booking_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Request</label>
    <referenceTo>Booking_Request__c</referenceTo>
    <relationshipLabel>Cost Sheets</relationshipLabel>
    <relationshipName>Cost_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Corpus_Fund__c.field-meta.xml
<CustomField>
    <fullName>Corpus_Fund__c</fullName>
    <formula>Unit__r.Corpus_Fund__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corpus Fund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/EB_Debris__c.field-meta.xml
<CustomField>
    <fullName>EB_Debris__c</fullName>
    <formula>Project__r.EB_Debris_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EB &amp; Debris</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Final_Price_Per_Sq_ft__c.field-meta.xml
<CustomField>
    <fullName>Final_Price_Per_Sq_ft__c</fullName>
    <label>Final Price Per Sq ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Floor_Rise_Charges__c.field-meta.xml
<CustomField>
    <fullName>Floor_Rise_Charges__c</fullName>
    <formula>(Floor_Rise_Charge__c* Super_Built_Up_Area__c) +((Floor_Rise_Charge__c/2)* Open_Terrace_Area__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Floor Rise Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>Total_Cost_Including_GST__c +  Corpus_Fund__c +  GST_for_Corpus_Fund__c +  Maintenance_Charges__c +  GST_for_Maintenance_Charge__c +  EB_Debris__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GST_Charges_On_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>GST_Charges_On_Total_Cost__c</fullName>
    <formula>GST__c *  Total_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Charges On Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GST_for_Corpus_Fund__c.field-meta.xml
<CustomField>
    <fullName>GST_for_Corpus_Fund__c</fullName>
    <formula>Unit__r.GST_on_Corpus_Fund__c *  Corpus_Fund__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST for Corpus Fund</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GST_for_Maintenance_Charge__c.field-meta.xml
<CustomField>
    <fullName>GST_for_Maintenance_Charge__c</fullName>
    <formula>Unit__r.GST_on_Maintenance_Charge__c *  Maintenance_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST for Maintenance Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Maintenance_Charges__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Charges__c</fullName>
    <formula>Unit__r.Maintenance_Charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maintenance Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Open_Terrace_Area__c.field-meta.xml
<CustomField>
    <fullName>Open_Terrace_Area__c</fullName>
    <label>Open Terrace Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Premium_Charges__c.field-meta.xml
<CustomField>
    <fullName>Premium_Charges__c</fullName>
    <formula>Unit__r.Premium_Charge__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Basic_Price__c + Floor_Rise_Charges__c + Premium_Charges__c + Other_Charges__c + Car_Parking_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Cost_Including_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Including_GST__c</fullName>
    <formula>Total_Cost__c + GST_Charges_On_Total_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost Including GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BulkApprovalComponent.cls
public with sharing class BulkApprovalComponent {

    public class ApprovalWrapper {
        @AuraEnabled public List<ApprovalRecord> records;
        @AuraEnabled public Integer totalPending;
    }

    public class ApprovalRecord {
        @AuraEnabled public String Id;
        @AuraEnabled public String Name;
        @AuraEnabled public String ObjectType; // Will now show Label instead of API Name
        @AuraEnabled public String Status;
        @AuraEnabled public String OwnerName;
        @AuraEnabled public DateTime SubmittedDate;
        @AuraEnabled public Boolean selected;
        @AuraEnabled public String ApprovalProcessName;
    }

    @AuraEnabled
    public static ApprovalWrapper getPendingApprovals() {
        ApprovalWrapper wrapper = new ApprovalWrapper();
        List<ApprovalRecord> approvalRecords = new List<ApprovalRecord>();

        try {
            // Fetch pending approval records
            List<ProcessInstanceWorkitem> workItems = [
                SELECT Id, ProcessInstance.TargetObjectId,
                       ProcessInstance.TargetObject.Type,
                       ProcessInstance.SubmittedBy.Name,
                       ProcessInstance.CreatedDate,
                       ProcessInstance.TargetObject.Name,
                	   ProcessInstance.ProcessDefinition.Name
                FROM ProcessInstanceWorkitem
                WHERE ProcessInstance.Status = 'Pending'
                ORDER BY ProcessInstance.CreatedDate DESC
                LIMIT 200
            ];

            // Cache for object labels to avoid repeated describe calls
            Map<String, String> objectLabelMap = new Map<String, String>();

            for (ProcessInstanceWorkitem workItem : workItems) {
                ApprovalRecord record = new ApprovalRecord();
                record.Id = workItem.ProcessInstance.TargetObjectId;
                record.Name = workItem.ProcessInstance.TargetObject.Name;

                String objectAPI = workItem.ProcessInstance.TargetObject.Type;

                // Fetch label using describe only once per object type
                if (!objectLabelMap.containsKey(objectAPI)) {
                    try {
                        Schema.DescribeSObjectResult objDesc = Schema.getGlobalDescribe().get(objectAPI).getDescribe();
                        objectLabelMap.put(objectAPI, objDesc.getLabel());
                    } catch (Exception e) {
                        objectLabelMap.put(objectAPI, objectAPI); // fallback to API name if describe fails
                    }
                }

                record.ObjectType = objectLabelMap.get(objectAPI);
                record.Status = 'Pending';
                record.OwnerName = workItem.ProcessInstance.SubmittedBy.Name;
                record.SubmittedDate = workItem.ProcessInstance.CreatedDate;
                
                record.ApprovalProcessName = workItem.ProcessInstance.ProcessDefinition.Name;
                
                record.selected = false;

                approvalRecords.add(record);
            }

            wrapper.records = approvalRecords;
            wrapper.totalPending = approvalRecords.size();
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving approvals: ' + e.getMessage());
        }

        return wrapper;
    }

    @AuraEnabled
    public static String getCurrentUserProfile() {
        return [SELECT Profile.Name FROM User WHERE Id = :UserInfo.getUserId()].Profile.Name;
    }
    
    //method to fetch modal information for Cancellation Approval
    @AuraEnabled
    public static Map<String, String> getApprovalModalInfo(String recordId) {
        Map<String, String> result = new Map<String, String>();
        try {
            // Get the work item to find the process name
            List<ProcessInstanceWorkitem> workItems = [
                SELECT Id, ProcessInstance.ProcessDefinition.Name
                FROM ProcessInstanceWorkitem 
                WHERE ProcessInstance.TargetObjectId = :recordId 
                LIMIT 1
            ];
            
            if (!workItems.isEmpty()) {
                String processName = workItems[0].ProcessInstance.ProcessDefinition.Name;
                result.put('approvalProcessName', processName);
                
                // If it's a Cancellation Approval, get the Booking's Cancellation Type
                if ('Cancellation Approval'.equals(processName)) {
                    // Query the Booking record for Cancellation Type
                    Booking__c booking = [SELECT Id, Cancellation_Type__c FROM Booking__c WHERE Id = :recordId LIMIT 1];
                    result.put('cancellationType', booking.Cancellation_Type__c);
                }
            }
        } catch (Exception e) {
            // Silent fail - if there's an error, modal will just show default view
            System.debug('Error fetching modal info: ' + e.getMessage());
        }
        return result;
    }
    
    @AuraEnabled
    public static void updateCancellationCharges(String recordId, Decimal cancellationCharges) {
        try {
            if (recordId != null && cancellationCharges != null) {
                Booking__c booking = new Booking__c(
                    Id = recordId,
                    Cancellation_Charges__c = cancellationCharges
                );
                update booking;
            }
        } catch (Exception e) {
            System.debug('Error updating cancellation charges: ' + e.getMessage());
            // Silent fail - don't throw exception as approval already succeeded
        }
    }

    @AuraEnabled
    public static void processBulkApproval(List<String> recordIds, String action, String comments) {
        try {
            List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();

            List<ProcessInstanceWorkitem> workItems = [
                SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId
                FROM ProcessInstanceWorkitem
                WHERE ProcessInstance.TargetObjectId IN :recordIds
            ];

            Map<Id, ProcessInstanceWorkitem> workItemMap = new Map<Id, ProcessInstanceWorkitem>();
            for (ProcessInstanceWorkitem workItem : workItems) {
                workItemMap.put(workItem.ProcessInstance.TargetObjectId, workItem);
            }

            for (String recordId : recordIds) {
                if (workItemMap.containsKey(recordId)) {
                    ProcessInstanceWorkitem workItem = workItemMap.get(recordId);

                    Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                    req.setWorkitemId(workItem.Id);
                    req.setAction(action);
                    req.setComments(comments);

                    requests.add(req);
                }
            }

            if (!requests.isEmpty()) {
                List<Approval.ProcessResult> results = Approval.process(requests);

                for (Approval.ProcessResult result : results) {
                    if (!result.isSuccess()) {
                        throw new AuraHandledException('Approval process failed for some records');
                    }
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException('Error processing approvals: ' + e.getMessage());
        }
    }
    
    // NEW: Method to get Cost Sheet details
    @AuraEnabled
    public static Quote__c getCostSheetDetails1(String recordId) {
        try {
            return [SELECT 
                    Name, Floor__c, BHK_Type__c, Balcony_Area__c, Super_Built_Up_Area__c,
                    Basic_Price__c, Floor_Rise_Charges__c, Premium_Charges__c, 
                    GST_Charges_On_Total_Cost__c, Corpus_Fund__c, Maintenance_Charges__c,
                    EB_Debris__c, Project__r.Name, Unit__r.Name,Unit__r.Block1__r.Name, Carpet_Area__c,
                    Open_Terrace_Area__c, Final_Price_Per_Sq_ft__c, Car_Parking_Charges__c,
                    Other_Charges__c, Total_Cost__c, Total_Cost_Including_GST__c,
                    GST_for_Corpus_Fund__c, GST_for_Maintenance_Charge__c, Grand_Total__c,
                    
                    Booking_Request__r.Name,Booking_Request__r.Customer_Name__c,
                	Booking_Request__r.Email__c,Booking_Request__r.Mobile__c  
                    FROM Quote__c 
                    WHERE Id = :recordId];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving cost sheet details: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static CostSheetWrapper getCostSheetDetails(String recordId) {
        CostSheetWrapper result = new CostSheetWrapper();
        try {
            // Fetch Quote details
            result.quoteDetails = [SELECT 
                    Name, Floor__c, BHK_Type__c, Balcony_Area__c, Super_Built_Up_Area__c,
                    Basic_Price__c, Floor_Rise_Charges__c, Premium_Charges__c, 
                    GST_Charges_On_Total_Cost__c, Corpus_Fund__c, Maintenance_Charges__c,
                    EB_Debris__c, Project__r.Name, Unit__r.Name,Unit__r.Block1__r.Name, Carpet_Area__c,
                    Open_Terrace_Area__c, Final_Price_Per_Sq_ft__c, Car_Parking_Charges__c,
                    Other_Charges__c, Total_Cost__c, Total_Cost_Including_GST__c,
                    GST_for_Corpus_Fund__c, GST_for_Maintenance_Charge__c, Grand_Total__c,
                    
                    Booking_Request__r.Name,Booking_Request__r.Customer_Name__c,
                	Booking_Request__r.Email__c,Booking_Request__r.Mobile__c  
                    FROM Quote__c 
                    WHERE Id = :recordId
            		];
            
            		// Fetch related Payment Schedule
            		result.paymentSchedules = [SELECT Id, Name,S_No__c,Received_Amount1__c,AmountB__c,Payment_percent__c FROM Payment_Schedule__c
                                       WHERE Cost_Sheet__c = :recordId ORDER BY S_No__c ASC ];

        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving cost sheet details: ' + e.getMessage());
        }
        return result;
    }
    
    public class CostSheetWrapper {
        @AuraEnabled public Quote__c quoteDetails;
        @AuraEnabled public List<Payment_Schedule__c> paymentSchedules;
    }
    
    @AuraEnabled
    public static BookingWrapper getBookingDetails(String recordId) {
        BookingWrapper result = new BookingWrapper();
        try {
            // Fetch booking details
            result.bookingInfo = [
                SELECT Name, Stage__c, Booking_Date__c, Project1__r.Name, Owner.Name,
                Plot__r.Name, FloorNo__c, Unit_BHK_Type__c,
                Flat_Actual_Number__c, Tower_Name__c,
                First_Applicant_Name__c, Profession1__c, Mobile_Primary1__c, Email1__c,
                Total__c, Total_received_Amount__c, Pending_Amount__c
                FROM Booking__c
                WHERE Id = :recordId
            ];
            
            //cost sheet
            result.costSheetDetails = [SELECT 
                    Name, Floor__c, BHK_Type__c, Balcony_Area__c, Super_Built_Up_Area__c,
                    Basic_Price__c, Floor_Rise_Charges__c, Premium_Charges__c, 
                    GST_Charges_On_Total_Cost__c, Corpus_Fund__c, Maintenance_Charges__c,
                    EB_Debris__c, Project__r.Name, Unit__r.Name,Unit__r.Block1__r.Name, Carpet_Area__c,
                    Open_Terrace_Area__c, Final_Price_Per_Sq_ft__c, Car_Parking_Charges__c,
                    Other_Charges__c, Total_Cost__c, Total_Cost_Including_GST__c,
                    GST_for_Corpus_Fund__c, GST_for_Maintenance_Charge__c, Grand_Total__c from Quote__c where Booking__c = :recordId]; 
            
            // Fetch payment schedules linked to booking
            result.paymentSchedules = [
                SELECT Id, Name, Payment_percent__c, AmountB__c,
                status__c, Pending_Amount__c
                FROM Payment_Schedule__c
                WHERE Booking__c = :recordId
                ORDER BY S_No__c ASC
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving booking details: ' + e.getMessage());
        }
        return result;
    }
    
    public class BookingWrapper {
        @AuraEnabled public Booking__c bookingInfo;
        @AuraEnabled public List<Payment_Schedule__c> paymentSchedules;
        @AuraEnabled public Quote__c costSheetDetails;
    }


}