force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Parking__c/Parking__c.object-meta.xml
<CustomObject>
    <label>Parking</label>
    <nameField>
        <displayFormat>PR - {00000}</displayFormat>
        <label>Parking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parkings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Parkings</relationshipLabel>
    <relationshipName>Parkings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parking__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stilt</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>1st Level</fullName>
            </value>
            <value>
                <fullName>2nd Level</fullName>
            </value>
            <value>
                <fullName>3rd Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parking__c/fields/Parking_Type__c.field-meta.xml
<CustomField>
    <fullName>Parking_Type__c</fullName>
    <label>Parking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parking__c/fields/Slot_Number__c.field-meta.xml
<CustomField>
    <fullName>Slot_Number__c</fullName>
    <label>Slot Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NCDController.cls
public class NCDController {
    public Id bookingId {get; set;}
    public String floor {get; set;}
    public Booking__c booking {get; set;}
    public Integer flatNo {get; set;}
    public String slots {get; set;}
    public String ptypes {get; set;}
    public String levels {get; set;}
    
    
    
    
    
    public NCDController(ApexPages.StandardController stdcontroller){
        bookingId = stdcontroller.getId();
        
        booking =[select Id, FloorNo__c, Flat_Number__c from Booking__c where Id =: bookingId ];
        floor = getFloorWithSuffix(booking.FloorNo__c);
        
        // Getting car parking informations from Parking object
        List<Parking__c> parking= [Select Id, Name,	Parking_Type__c,Level__c, Slot_Number__c From Parking__c Where Booking__c = : bookingId];
        Set<String> slot = new Set<String>();
        Set<String> pType = new Set<String>();
        Set<String> level = new Set<String>();
        
        
        for(Parking__c p:parking){
            if(p.Slot_Number__c !=null){
                slot.add(String.valueOf(p.Slot_Number__c));
            }
            if(p.Parking_Type__c !=null){
                pType.add(String.valueOf(p.Parking_Type__c));
            }
            if(p.Parking_Type__c !=null){
                level.add(String.valueOf(p.Level__c));
            }
            
            
        }
        // Converting to comma seperated values
        slots = String.join(new List<String>(slot), ', ');
        pTypes = String.join(new List<String>(pType), ', '); 
        levels = String.join(new List<String>(level), ', ');
        
        
        if(booking.Flat_Number__c != null){
            flatNo = Integer.valueOf(String.valueOf(booking.Flat_Number__c));
        }
        
    }
    
    /////// Formatting Floor Number
    public static String getFloorWithSuffix(String floorNumber) {
        if (floorNumber == null) {
            return null;
        }
        
        String floorStr = String.valueOf(floorNumber); // Convert the floor number to a string
        String suffix = 'th'; // Default suffix is "th"
        
        // Handle the special case for numbers 11-13 (e.g., 11th, 12th, 13th)
        if (floorStr.endsWith('11') || floorStr.endsWith('12') || floorStr.endsWith('13')) {
            suffix = 'th';
        } else {
            // Get the last character of the string and determine the suffix
            String lastChar = floorStr.substring(floorStr.length() - 1);
            if (lastChar == '1') {
                suffix = 'st';
            } else if (lastChar == '2') {
                suffix = 'nd';
            } else if (lastChar == '3') {
                suffix = 'rd';
            }
        }
        
        return floorNumber + suffix;
    }
    
    
}