force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Interest_From_PS__c.field-meta.xml
<CustomField>
    <fullName>Interest_From_PS__c</fullName>
    <label>Interest From PS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Waive_Off__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Waive_Off__c</fullName>
    <label>Total Waive Off Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_A__c.field-meta.xml
<CustomField>
    <fullName>Interest_A__c</fullName>
    <description>Sum of Total Interest Amount form Interest Line item</description>
    <label>Interest from IL</label>
    <summarizedField>Interest_Amount_Line_Item__c.Total_Interest_Amount__c</summarizedField>
    <summaryForeignKey>Interest_Amount_Line_Item__c.Payment_Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid (From RL)</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Payment_Type__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BookingRollupHandler.cls
public class BookingRollupHandler {
    public static void updateBookingRollups(Set<Id> bookingIds) {
        bookingIds.remove(null);
        
        try{
            Map<Id, AggregateResult> bookingAggMap = new Map<Id, AggregateResult>(
                [SELECT Booking__c,
                 SUM(Waive_Off_Amount__c) Total_Interest_Waive_Off,
                 SUM(Interest_A__c) 	Interest_From_PS,
                 SUM(Interest_Paid__c) Interest_Paid
                 FROM Payment_Schedule__c
                 WHERE Booking__c IN :bookingIds
                 GROUP BY Booking__c]
            );
            
            List<Booking__c> bookingsToUpdate = new List<Booking__c>();
            
            for (Id bookingId : bookingIds) {
                AggregateResult agg = bookingAggMap.get(bookingId);
                Booking__c book = new Booking__c(Id = bookingId);
                
                book.Total_Interest_Waive_Off__c = (agg != null && agg.get('Total_Interest_Waive_Off') != null) ? (Decimal)agg.get('Total_Interest_Waive_Off') : 0;
                book.Interest_From_PS__c = (agg != null && agg.get('Interest_From_PS') != null) ? (Decimal)agg.get('Interest_From_PS') : 0;
                book.Interest_Paid__c = (agg != null && agg.get('Interest_Paid') != null) ? (Integer)agg.get('Interest_Paid') : 0;
                
                bookingsToUpdate.add(book);
            }
            
            if (!bookingsToUpdate.isEmpty()) {
                update bookingsToUpdate;
            }
        }
        catch(exception exe){
            
        }
    }
}