force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total__c -   Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Consideration_with_taxes_and_other__c.field-meta.xml
<CustomField>
    <fullName>Total_Consideration_with_taxes_and_other__c</fullName>
    <formula>/*IF(ISNULL(Quote__c),Total_With_Taxswap__c,Quote__r.Total_Consideration_with_taxes_and_other__c )*/
1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Consideration with taxes and other</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_received_Amount__c</fullName>
    <label>Total Received Amount</label>
    <summarizedField>Receipt__c.Total_Received_Amount__c</summarizedField>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <description>Payment_percent__c *  Booking__r.Total__c</description>
    <formula>Cost_Sheet__r.Grand_Total__c  * Payment_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>/*ABS(Balance_Amount__c -  Received_Amount1__c)*/
 AmountB__c  - Received_Amount1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rec-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <formula>TEXT( Booking__r.Bank__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Check_Transaction_Nmber__c.field-meta.xml
<CustomField>
    <fullName>Check_Transaction_Nmber__c</fullName>
    <label>Cheque no / Transaction Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_date__c</fullName>
    <label>Receipt Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Total_Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Amount__c</fullName>
    <label>Total Received Amount</label>
    <summarizedField>Receipt_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Receipt_Line_Item__c.Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/convertValueToWords.cls
public class convertValueToWords {
    public Id bookingId;
    public string totalPendingInIndia{get;set;}
    public string totalPendingWords{get;set;}
    public string totalCostInString{get;set;}
    public string loanAmountInString{get;set;}
    public string loanAmountInWords{get;set;}
    public string tillDateReceived{get;set;}
    public string TotalCostAmountInWords{get;set;}
    public string BookingAmount{get;set;}
    public string projectSpecification {get;set;}
    public String totlreceivedinIndian {get;set;}
    public String totlbasicPriceinIndian {get;set;}
    public String totltaxinIndian {get;set;}
    
    public List<paySchWrapper> payList {get;set;}
    public List<recWrapper> recpList {get;set;}
    public class paySchWrapper{
        public string Name{get;set;}
        public Decimal Payment_percent{get;set;}
        public boolean isConstruction{get;set;}
        public boolean isSale{get;set;}
        public string amount{get;set;}
        public Decimal S_No{get;set;}
    }
    
    public class recWrapper{
        public string checkNo{get;set;}
        public Date repDate{get;set;}
        public String amountInWords{get;set;}
        public string BankName{get;set;}
        public string branchName{get;set;}
    }
    
    public convertValueToWords(ApexPages.StandardController stdController) {
        bookingId = (Id)stdController.getId();
        Booking__c bk = [select id,name,Basic_Price__c,Total_received_Amount__c,Pending_Amount__c,Sanctioned_Amount__c,Total_Consideration_with_taxes_and_other__c from Booking__c where id =: bookingId];
        
        List<Receipt__c> repList = [Select Id,Check_Transaction_Nmber__c,Receipt_date__c,Total_Received_Amount__c,Bank_Name__c from Receipt__c where Booking__c=:bk.Id order by  Receipt_date__c asc];
        List<paySchWrapper> samp = new List<paySchWrapper>();
        List<Payment_Schedule__c> payListStan = [select id,name,S_No__c,Payment_Percent__c,AmountB__c,Amount__c from Payment_Schedule__c where Booking__c =:bk.id ];
        for(Payment_Schedule__c ps : payListStan){
            paySchWrapper pw = new paySchWrapper();
            pw.Name = ps.Name;
            pw.Payment_percent = ps.Payment_Percent__c;
            pw.amount = ps.AmountB__c.setScale(2).format();
            pw.S_No = ps.S_No__c;
            samp.add(pw);
        }
        
		payList =  samp;  
        
        List<recWrapper> repLitsItems = new List<recWrapper>();
        for(Receipt__c ps : repList){
            recWrapper pw = new recWrapper();
            pw.checkNo = ps.Check_Transaction_Nmber__c;
            pw.repDate = ps.Receipt_date__c;
            pw.amountInWords = ps.Total_Received_Amount__c.setScale(2).format();
            pw.BankName = ps.Bank_Name__c;
            repLitsItems.add(pw);
        }
        
        recpList = repLitsItems;
        
        totalCostInString = bk.Total_Consideration_with_taxes_and_other__c.setScale(2).format();
        totlreceivedinIndian = bk.Total_received_Amount__c.setScale(2).format();
        totalPendingInIndia = bk.Pending_Amount__c.setScale(2).format();
        NumberTOWordConvertion nwcObj = new NumberTOWordConvertion();
        if(bk.Sanctioned_Amount__c != null){
            loanAmountInString = bk.Sanctioned_Amount__c.setScale(2).format();
            loanAmountInWords = nwcObj.getNumberTOWordConvertion(bk.Sanctioned_Amount__c);
        }
        if(bk.Basic_Price__c != null){
            totlbasicPriceinIndian = bk.Basic_Price__c.setScale(2).format();
        }
        TotalCostAmountInWords = nwcObj.getNumberTOWordConvertion(bk.Total_Consideration_with_taxes_and_other__c);
        //BookingAmount = nwcObj.getNumberTOWordConvertion(bk.Booking_Amount__c);
        totalPendingWords = nwcObj.getNumberTOWordConvertion(bk.Pending_Amount__c);
        tillDateReceived = nwcObj.getNumberTOWordConvertion(bk.Total_received_Amount__c);
    }

}