force-app/main/default/objects/Booking_Request__c/Booking_Request__c.object-meta.xml
<CustomObject>
    <label>Booking Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Booking Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Request__c/fields/Blocked_Price__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Price__c</fullName>
    <label>Blocked Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Unit__r.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Booking Requests</relationshipLabel>
    <relationshipName>Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Block1__c.field-meta.xml
<CustomField>
    <fullName>Block1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Is_PSA_Unit__c.field-meta.xml
<CustomField>
    <fullName>Is_PSA_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PSA Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT RELEASE FOR SALE</fullName>
                <label>Not Release For Sale</label>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSAUnitController.cls
public class PSAUnitController {
    
     public class DataWrapper{
        @AuraEnabled 
        public List<Plot__c> PlotLst {get; set;}
        @AuraEnabled 
        public decimal BlockedPrice {get; set;}
     }
    
    @AuraEnabled
    public static DataWrapper fetchRecords(String BookingReqId) {
        DataWrapper dtwrp = new DataWrapper();
        
        system.debug('In Apex');
        Booking_Request__c BkRec = [select id,name,Unit__c,Unit__r.Project__c,Blocked_Price__c from Booking_Request__c where Id=:BookingReqId limit 1];
        string PrjId = BkRec.Unit__r.Project__c;
        dtwrp.BlockedPrice = BkRec.Blocked_Price__c;
        
        List<Plot__c> ptLst = [select id,name,Block1__c,Project__c,	Is_PSA_Unit__c from Plot__c where Project__c =: PrjId and Status__c ='Available' and Is_PSA_Unit__c = false];
        dtwrp.PlotLst = ptLst;
        
        return dtwrp;
    }
}