force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <value>Apartments</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tower</relationshipLabel>
    <relationshipName>Block</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/First_Disbursement_Received__c.field-meta.xml
<CustomField>
    <fullName>First_Disbursement_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Disbursement Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Master Payment Schedules</relationshipLabel>
    <relationshipName>Master_payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Floor_Rise__c.field-meta.xml
<CustomField>
    <fullName>Floor_Rise__c</fullName>
    <label>Floor Rise</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Premium_Charge__c.field-meta.xml
<CustomField>
    <fullName>Premium_Charge__c</fullName>
    <label>Premium Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Price_Per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Sq_Ft__c</fullName>
    <label>Price Per Sq Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Apartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Apartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestSwappingUnitController.cls
@isTest
public class TestSwappingUnitController {

    @testSetup
    static void setupData() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User financeUser = new User(
            Username = 'swapfin-' + System.currentTimeMillis() + '@test.com',
            Email = 'swapfin@test.com',
            LastName = 'SwapFinance',
            Alias = 'sfin',
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = p.Id
        );
        insert financeUser;

        Project__c proj = new Project__c(
            Name = 'Jains Anushree',
            Project_Type__c = 'Apartments',
            Finance_User__c = financeUser.Id
        );
        insert proj;

        Plot__c plot = new Plot__c(
            Name = 'Test Plot',
            Block__c = 'A2',
            Project__c = proj.Id,
            Project_Type__c = 'Apartments',
            Floor__c = '1',
            Price_Per_Sq_Ft__c = 2000,
            Floor_Rise__c = 100,
            Premium_Charge__c = 50
        );
        insert plot;

        Booking__c booking = new Booking__c(
            Project__c = 'Jains Anushree',
            Project1__c = proj.Id,
            Plot__c = plot.Id,
            Payment_Type__c = 'Standard',
            Sale_Agreement_Completed__c = false,
            First_Disbursement_Received__c = false
        );
        insert booking;

        Master_Payment_Schedule__c mps = new Master_Payment_Schedule__c(
            Name = 'Test Master Schedule',
            Project__c = proj.Id,
            Project_Type__c = 'Apartments',
            S_No__c = 1,
            Payment_Percent__c = 10,
            Amount__c = 1000
        );
        insert mps;
    }

    // -------------------- Test getBooking --------------------
    @isTest
    static void test_getBooking() {
        Booking__c booking = [SELECT Id FROM Booking__c LIMIT 1];

        Test.startTest();
        Booking__c result = SwappingUnitController.getBooking(booking.Id);
        Test.stopTest();

        System.assertEquals(booking.Id, result.Id, 'Booking should be fetched correctly');
    }

    // -------------------- Test getUnit --------------------
    @isTest
    static void test_getUnit() {
        Plot__c plot = [SELECT Id FROM Plot__c LIMIT 1];

        Test.startTest();
        Plot__c result = SwappingUnitController.getUnit(plot.Id);
        Test.stopTest();

        System.assertEquals(plot.Id, result.Id, 'Plot should be fetched correctly');
    }

    // -------------------- Test saveOppPlot --------------------
    @isTest
    static void test_saveOppPlot() {
        Lead testLead = new Lead(
            LastName = 'Test Lead',
            Company = 'Test Company'
        );
        insert testLead;

        Booking__c booking = [SELECT Id FROM Booking__c LIMIT 1];
        booking.SLead__c = testLead.Id;
        update booking;

        Booking__c oppBooking = new Booking__c(
            Id = booking.Id,
            Swap_Unit__c = 'B-202'
        );

        Test.startTest();
        String resultId = SwappingUnitController.saveOppPlot(oppBooking, booking.Id);
        Test.stopTest();

        System.assertEquals(booking.Id, resultId, 'Returned Id should match booking Id');
    }

    // -------------------- Test getPaymentTypePicklistValues --------------------
    @isTest
    static void test_getPaymentTypePicklistValues() {
        Test.startTest();
        List<String> picklistValues = SwappingUnitController.getPaymentTypePicklistValues();
        Test.stopTest();

        System.assertNotEquals(null, picklistValues, 'Picklist values should not be null');
    }

    // -------------------- Test getPaymentSchedules --------------------
    @isTest
    static void test_getPaymentSchedules() {
        Project__c proj = [SELECT Id, Name FROM Project__c LIMIT 1];

        Test.startTest();
        List<Master_Payment_Schedule__c> schedules = SwappingUnitController.getPaymentSchedules('Standard', proj.Name);
        Test.stopTest();

        System.assert(schedules.size() > 0, 'Should fetch Master Payment Schedule records');
    }

    // -------------------- Test insertSchedules --------------------
    @isTest
    static void test_insertSchedules() {
        Booking__c booking = [SELECT Id FROM Booking__c LIMIT 1];

        Payment_Schedule__c pay1 = new Payment_Schedule__c(
            Name = 'Test Payment 1',
            Payment_Percent__c = 10,
            Amount__c = 5000,
            Payment_Due_Date__c = Date.today(),
            S_No__c = 1,
            Booking__c = booking.Id
        );

        List<Payment_Schedule__c> payList = new List<Payment_Schedule__c>{ pay1 };

        Test.startTest();
        SwappingUnitController.insertSchedules(payList, booking.Id);
        Test.stopTest();

        List<Payment_Schedule__c> inserted = [
            SELECT Id FROM Payment_Schedule__c WHERE Booking__c = :booking.Id
        ];
        System.assert(inserted.size() > 0, 'Payment schedules should be inserted successfully');
    }
}