force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <value>Apartments</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tower</relationshipLabel>
    <relationshipName>Block</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Interest_Waive_Off__c.field-meta.xml
<CustomField>
    <fullName>Interest_Waive_Off__c</fullName>
    <label>Interest Waive Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total__c -   Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Property_Type_For__c.field-meta.xml
<CustomField>
    <fullName>Property_Type_For__c</fullName>
    <formula>TEXT(Plot__r.Project__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Type For</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Cost_Sheet__r.Grand_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Waive_Off__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Waive_Off__c</fullName>
    <label>Total Waive Off Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Plot__r.Block1__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{000}</displayFormat>
        <label>Demand Raised Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand_Raised__c/fields/Current_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Current_Milestone__c</fullName>
    <label>Current Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Finance_User__c.field-meta.xml
<CustomField>
    <fullName>Finance_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Grand_Total_In_Words__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_In_Words__c</fullName>
    <label>Grand Total In Words</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Intrest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Intrest_Amount__c</fullName>
    <label>Interest Amount Pending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Milestone_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Completed_Date__c</fullName>
    <label>Milestone Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Milestone_Number__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Number__c</fullName>
    <label>Milestone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Demand Raised</relationshipLabel>
    <relationshipName>Demand_Raised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand_Raised__c/fields/Total_Paid_Till__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Till__c</fullName>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Master Payment Schedules</relationshipLabel>
    <relationshipName>Master_payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Master Payment Schedules</relationshipLabel>
    <relationshipName>Master_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <description>Payment_percent__c *  Booking__r.Total__c</description>
    <formula>Cost_Sheet__r.Grand_Total__c  * Payment_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <formula>/*If( Include_Interest__c ,if(Payment_Due_Date__c &lt; TODAY() &amp;&amp;  ISBLANK(Last_Payment_Date__c),
			(Pending_Amount__c *  Interest_Percent__c * (TODAY() - Payment_Due_Date__c))/365 ,
			if(Last_Payment_Date__c &lt; TODAY() &amp;&amp; !ISBLANK(Last_Payment_Date__c),
						(Pending_Amount__c *  Interest_Percent__c * (TODAY() - Last_Payment_Date__c))/365, 0.0)),0)*/

IF(
				Include_Interest__c,
				IF(
								!ISBLANK(Payment_Due_Date__c) &amp;&amp; Payment_Due_Date__c &lt; TODAY(),
								 MAX(((Pending_Amount__c * Interest_Percent__c * (TODAY() - Payment_Due_Date__c)) / 365),0),0),0) 

								/*IF(
												ISBLANK(Payment_Due_Date__c) &amp;&amp; !ISBLANK(Demand_Date__c) &amp;&amp; Demand_Date__c,
												IF(
																!ISBLANK(Interest_Change_Date__c) &amp;&amp; Interest_Change_Date__c &gt; Last_Payment_Date__c,
																(Pending_Amount__c * Interest_Percent__c * (TODAY() - Interest_Change_Date__c)) / 365,
																(Pending_Amount__c * Interest_Percent__c * (TODAY() - Last_Payment_Date__c)) / 365
												),
												0.0
								)
				),
				0
)*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid (From RL)</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Payment_Type__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>/*ABS(Balance_Amount__c -  Received_Amount1__c)*/
 AmountB__c  - Received_Amount1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received Amount through Receipts</label>
    <summarizedField>Receipt_Line_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Demanded</fullName>
                <isActive>false</isActive>
                <label>Demanded</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentScheduleCustomSelectController.cls
public class PaymentScheduleCustomSelectController {
    @AuraEnabled
    public static List<Payment_schedule__c> getPaymentSchedules(Id bookingId) {
        return [ SELECT Id, Name, status__c,S_No__c, Pending_Amount__c FROM Payment_schedule__c WHERE Booking__c = :bookingId ORDER BY S_No__c asc ];
    }
    @AuraEnabled
    public static String raiseDemand(id milestoneId, String demandEmailContent, list<id> documentIds){
        Payment_Schedule__c psRecord = [ SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c, Booking__r.Property_Type_For__c, Booking__r.Tower__c, Booking__c, Master_Payment_Schedule__r.S_No__c, Master_Payment_Schedule__c FROM Payment_Schedule__c WHERE Id = :milestoneId ];
        Booking__c book = [SELECT Id,Interest_Waive_Off__c,Total_Interest_Waive_Off__c,GST__c,Debit_Amount__c,Total__c,Finance_User__c, Name, Project__c,Project1__r.Name, Property_Type_For__c, Block__c, Tower__c FROM Booking__c WHERE Id = :psRecord.Booking__c];
        
        String result = '';    
        if (psRecord.Booking__r.Property_Type_For__c == 'Apartments') {
            result = apartmentScheduleCalculations(milestoneId,psRecord.Master_Payment_Schedule__c,book, demandEmailContent, documentIds);
            return result;
        }else if (psRecord.Booking__r.Property_Type_For__c == 'Villas')  {
            result = villaScheduleCalculations(milestoneId, book, demandEmailContent, documentIds);
            return result;
        }else{
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No "Property Type" selected for this booking.'));
            return '';
        }
    }
    public static String apartmentScheduleCalculations(Id milestoneId,Id masterId,Booking__c book, String emailContent,list<id> documentIds) {
        String totalAmountPayableInWords = '';
        Decimal totalAmountPayable =0;
        Decimal paidTillPrevMilestone =0;
        String currentCompletedStage = '';
        date demandDueDate;
        Decimal currentMilestonePaymentPercent = 0;
        String currentMilestoneNumber = '';
        date currentCompletedStageDate;
        Decimal totAmtDueTillPrevMilestone = 0;
        Decimal interestPaidTillPrevious = 0;
        Decimal interestDelayTillPrevious = 0;
        Decimal balanceDueTillPrevMilestone = 0;
        Decimal milestonePaymentPercentTill = 0;
        Decimal presentDue = 0;
        Decimal TDSonePercentage = 0;
        Decimal balanceInterest = 0;
        
        list<Master_Payment_Schedule__c> msRecordList = [ SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c FROM Master_Payment_Schedule__c WHERE Id =:masterId Limit 1 ];
        
        if (msRecordList.isEmpty()) {
            // Handle case where no milestones are completed
            currentCompletedStage = 'No milestone completed';
            currentCompletedStageDate = null;
            demandDueDate = null;
            currentMilestonePaymentPercent = 0;
            currentMilestoneNumber = null;
            totalAmountPayableInWords = 'Zero';
            
            // Optionally, you could log or show a message
            System.debug('No milestone completed for the booking.');
           return 'ERROR: No milestone completed for the booking';
        }
        
        Master_Payment_Schedule__c msRecord = msRecordList[0]; 
        
        if (msRecord != null) {
            currentCompletedStage = msRecord.Name;
            currentCompletedStageDate = msRecord.Completed_Date__c;
            demandDueDate = System.today().addDays(15);
            currentMilestonePaymentPercent = msRecord.Payment_percent__c != null ? msRecord.Payment_percent__c.setScale(0) : 0;
            
            Decimal stNumber = msRecord.S_No__c;
            if (stNumber != null) {
                currentMilestoneNumber = getMilestoneLabel(stNumber.intValue());
            }
            
            AggregateResult[] aggregateResults = [
                SELECT SUM(Pending_Amount__c) totalPendingAmount, SUM(Interest_Amount__c) totalInterestAmount,
                SUM(AmountB__c) totalPayableAmount,
                SUM(Interest_Up_to_Date__c) totalInterestUplodate, SUM(Interest_Paid__c) totalInterestPaid,
                SUM(Payment_percent__c) paymentPercentageTill
                FROM Payment_Schedule__c
                WHERE Master_Payment_Schedule__r.Status__c = 'Completed' 
                AND Master_Payment_Schedule__r.S_No__c < :msRecord.S_No__c 
                AND Booking__c = :book.Id
            ];

            system.debug('aggregateResults'+aggregateResults);
            Decimal totalPendingAmount = 0;
            Decimal totalInterestAmount = 0;
            Decimal totalPayableAmount = 0;
            Decimal totalReceivedAmount = 0;
            Decimal paidPreMilestone = 0;
            Decimal totalInterestUplodateAmount = 0;
            Decimal totalInterestPaid = 0;
            Decimal waveOff = 0;
            Decimal milestonePaymentPercent = 0;
            Decimal balanceDueTillPrevMilestoneMod = 0;
            Decimal milestonePaymentPercentResult =0;
            if (!aggregateResults.isEmpty()) {
                totalPendingAmount = (Decimal) aggregateResults[0].get('totalPendingAmount') != null ? (Decimal) aggregateResults[0].get('totalPendingAmount') : 0;
                totalInterestAmount = (Decimal) aggregateResults[0].get('totalInterestAmount') != null ? (Decimal) aggregateResults[0].get('totalInterestAmount') : 0;
                totalPayableAmount = (Decimal) aggregateResults[0].get('totalPayableAmount') != null ? (Decimal) aggregateResults[0].get('totalPayableAmount') : 0;
                totalInterestUplodateAmount = (Decimal) aggregateResults[0].get('totalInterestUplodate') != null ? (Decimal) aggregateResults[0].get('totalInterestUplodate') : 0;
                totalInterestPaid = (Decimal) aggregateResults[0].get('totalInterestPaid') != null ? (Decimal) aggregateResults[0].get('totalInterestPaid') : 0;
                milestonePaymentPercent = aggregateResults[0].get('paymentPercentageTill') != null ? (Decimal) aggregateResults[0].get('paymentPercentageTill') : 0;
            }
            system.debug('paidPreMilestone'+paidPreMilestone);
            totAmtDueTillPrevMilestone = totalPayableAmount;
            interestPaidTillPrevious = totalInterestPaid;
            interestDelayTillPrevious = (totalInterestUplodateAmount > 0) ? (totalInterestUplodateAmount) : totalInterestAmount;
            
            double paidTotalAmount = 0;
            AggregateResult presentDueResult = [
                SELECT SUM(AmountB__c) totalAmountB,SUM(Payment_percent__c) paymentPercentageTill
                FROM Payment_Schedule__c
                WHERE Master_Payment_Schedule__r.S_No__c = :msRecord.S_No__c
                AND Booking__c = :book.Id
            ];
            Decimal presentDueAmount = 0;
            if (presentDueResult != null && presentDueResult.get('totalAmountB') != null) {
                presentDueAmount = (Decimal) presentDueResult.get('totalAmountB');
            }
            if (presentDueResult != null && presentDueResult.get('paymentPercentageTill') != null) {
                milestonePaymentPercentResult = milestonePaymentPercent + currentMilestonePaymentPercent;
            }
            
            if (book.Total_Interest_Waive_Off__c != null) {
                waveOff = book.Total_Interest_Waive_Off__c;
            }
            
            AggregateResult totalReceied = [
                SELECT SUM(Received_Amount1__c) totalReceivedAmount
                FROM Payment_Schedule__c
                WHERE Booking__c = :book.Id
            ];
            
            if (totalReceied != null && totalReceied.get('totalReceivedAmount') != null) {
                paidTotalAmount = (Decimal) totalReceied.get('totalReceivedAmount');
            }
            if (book.Debit_Amount__c != null){
                paidTotalAmount-= book.Debit_Amount__c;
            }
            paidTillPrevMilestone =  paidTotalAmount;          
            balanceDueTillPrevMilestoneMod = totalPayableAmount - paidTotalAmount;
            if(balanceDueTillPrevMilestoneMod > 0){
                balanceDueTillPrevMilestone = balanceDueTillPrevMilestoneMod;
            }
            milestonePaymentPercentTill = milestonePaymentPercentResult.setScale(0);
            presentDue = presentDueAmount;
            
            Decimal gstPercentage = (book.GST__c != null) ? book.GST__c / 100 : 0;
            Decimal amountExcludingGST = presentDue / (1 + gstPercentage);
            TDSonePercentage = amountExcludingGST * 0.01; 
            
            balanceInterest = interestDelayTillPrevious - waveOff - interestPaidTillPrevious;
            
            double totalAmount = 0;
            
            if(book.Project1__r.Name == 'MAHENDRA AARYA'){
                totalAmount = (balanceDueTillPrevMilestoneMod + balanceInterest + presentDue).setScale(0);
            }else if(book.Project1__r.Name == 'MAHENDRA ARTO HELIX'){
                totalAmount = (balanceDueTillPrevMilestoneMod + balanceInterest + presentDue - TDSonePercentage).setScale(0) ;
            }
            
            if(totalAmount > -1){
                totalAmountPayable = totalAmount;
            }
            
            NumberTOWordConvertion convert = new NumberTOWordConvertion();
            if (totalAmountPayable != null && totalAmountPayable > -1) {
                totalAmountPayableInWords = convert.getNumberTOWordConvertion(totalAmountPayable);
            }
            
            String fileIdsString = String.join(documentIds, ',');
            
            Demand_Raised__c re = new Demand_Raised__c();
            re.Total_Amount_till_Current_Milestone__C = totalPayableAmount;
            re.Total_Paid_Till__c = paidTotalAmount > 0 ? paidTotalAmount : 0;
            re.Previous_pendings__c = balanceDueTillPrevMilestone;
            re.Interest_Delay_Till_Previous_Milestone__c = totalInterestUplodateAmount;
            re.Total_Interest_Paid__c = totalInterestPaid;
            re.Current_Demand_amount__c = presentDue;
            re.Intrest_Amount__c = balanceInterest;
            re.Grand_Total__c = totalAmountPayable;
            re.Grand_Total_In_Words__c = totalAmountPayableInWords;
            re.Current_Milestone__c = currentCompletedStage;
            re.Milestone_Completed_Date__c = currentCompletedStageDate;
            re.Milestone_Number__c = currentMilestoneNumber;
            re.Due_Date__c = System.Now().addDays(7);
            re.Current_Milestone_Percentage__c = currentMilestonePaymentPercent;
            re.Total_Percentage_till_Current_Milestone__c = milestonePaymentPercentTill;
            re.TDS_Amount__c = TDSonePercentage;
            re.Booking__c = Book.Id;
            re.Total_Flat_Cost__c = Book.Total__c;
            re.Finance_User__c = book.Finance_User__c;
            re.Demand_Email_Content__c = emailContent;
            re.Demand_Content_Ids__c = fileIdsString;
            re.Demanded_Date__c = System.Now();
            re.Payment_schedule__c = milestoneId;
            
            try {
                insert re;
                return 'Demand Raise records created.';
            } catch (DmlException e) {
                System.debug('Error inserting record: ' + e.getMessage());
                return 'Error: ' + e.getMessage();
            }
        }
        else{
            return 'ERROR: No milestone records';
        }
    }
    
    public static String villaScheduleCalculations(Id scheduleId,Booking__c book, String emailContent,list<id> documentIds) {
        
        String totalAmountPayableInWords = '';
        Decimal totalAmountPayable =0;
        Decimal paidTillPrevMilestone =0;
        String currentCompletedStage = '';
        date demandDueDate;
        Decimal currentMilestonePaymentPercent = 0;
        String currentMilestoneNumber = '';
        date currentCompletedStageDate;
        Decimal totAmtDueTillPrevMilestone = 0;
        Decimal interestPaidTillPrevious = 0;
        Decimal interestDelayTillPrevious = 0;
        Decimal balanceDueTillPrevMilestone = 0;
        Decimal milestonePaymentPercentTill = 0;
        Decimal presentDue = 0;
        Decimal TDSonePercentage = 0;
        Decimal balanceInterest = 0;

        
        List<Payment_Schedule__c> psRecordList = [
            SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c
            FROM Payment_Schedule__c
            WHERE Id = :scheduleId
            ORDER BY S_No__c DESC LIMIT 1
        ];
        if (psRecordList.isEmpty()) {
            // Handle case where no milestones are completed
            currentCompletedStage = 'No milestone completed';
            currentCompletedStageDate = null;
            demandDueDate = null;
            currentMilestonePaymentPercent = 0;
            currentMilestoneNumber = null;
            totalAmountPayableInWords = 'Zero';
            
            // Optionally, you could log or show a message
            System.debug('No milestone completed for the booking.');
            return 'ERROR: No milestone completed for the booking.';
        }
        
        Payment_Schedule__c psRecord = psRecordList[0]; 
        
        if (psRecord != null) {
            currentCompletedStage = psRecord.Name;
            currentCompletedStageDate = psRecord.Completed_Date__c;
            demandDueDate = System.today().addDays(7);
            currentMilestonePaymentPercent = psRecord.Payment_percent__c != null ? psRecord.Payment_percent__c.setScale(0) : 0;
            
            Decimal stNumber = psRecord.S_No__c;
            if (stNumber != null) {
                currentMilestoneNumber = getMilestoneLabel(stNumber.intValue());
            }
            
            AggregateResult[] aggregateResults = [
                SELECT SUM(Pending_Amount__c) totalPendingAmount, 
                SUM(Interest_Amount__c) totalInterestAmount,
                SUM(AmountB__c) totalPayableAmount,
                SUM(Interest_Up_to_Date__c) totalInterestUplodate, 
                SUM(Interest_Paid__c) totalInterestPaid,
                SUM(Payment_percent__c) paymentPercentageTill
                FROM Payment_Schedule__c
                WHERE Status__c = 'Completed' 
                AND S_No__c < :psRecord.S_No__c 
                AND Booking__c = :book.Id
            ];
            
            Decimal totalPendingAmount = 0;
            Decimal totalInterestAmount = 0;
            Decimal totalPayableAmount = 0;
            Decimal paidPreMilestone = 0;
            Decimal totalInterestUplodateAmount = 0;
            Decimal totalInterestPaid = 0;
            Decimal waveOff = 0;
            Decimal milestonePaymentPercent =0;
            Decimal balanceDueTillPrevMilestoneMod = 0;
            if (!aggregateResults.isEmpty()) {
                totalPendingAmount = (Decimal) aggregateResults[0].get('totalPendingAmount') != null ? (Decimal) aggregateResults[0].get('totalPendingAmount') : 0;
                totalInterestAmount = (Decimal) aggregateResults[0].get('totalInterestAmount') != null ? (Decimal) aggregateResults[0].get('totalInterestAmount') : 0;
                totalPayableAmount = (Decimal) aggregateResults[0].get('totalPayableAmount') != null ? (Decimal) aggregateResults[0].get('totalPayableAmount') : 0;
                totalInterestUplodateAmount = (Decimal) aggregateResults[0].get('totalInterestUplodate') != null ? (Decimal) aggregateResults[0].get('totalInterestUplodate') : 0;
                totalInterestPaid = (Decimal) aggregateResults[0].get('totalInterestPaid') != null ? (Decimal) aggregateResults[0].get('totalInterestPaid') : 0;
                milestonePaymentPercent = (Decimal) aggregateResults[0].get('paymentPercentageTill') != null ? (Decimal) aggregateResults[0].get('paymentPercentageTill') : 0;
            }
            
            totAmtDueTillPrevMilestone = totalPayableAmount;
            interestPaidTillPrevious = totalInterestPaid;
            interestDelayTillPrevious = (totalInterestUplodateAmount > 0) ? (totalInterestUplodateAmount) : totalInterestAmount;
            
            double paidTotalAmount = 0;
            AggregateResult presentDueResult = [
                SELECT SUM(AmountB__c) totalAmountB,
                SUM(Payment_percent__c) paymentPercentageTill
                FROM Payment_Schedule__c
                WHERE S_No__c = :psRecord.S_No__c
                AND Booking__c = :book.Id
            ];
            
            Decimal presentDueAmount = 0;
            if (presentDueResult != null && presentDueResult.get('totalAmountB') != null) {
                presentDueAmount = (Decimal) presentDueResult.get('totalAmountB');
            }
            presentDue = presentDueAmount;
            
            Decimal gstPercentage = (book.GST__c != null) ? book.GST__c / 100 : 0;
            Decimal amountExcludingGST = presentDue / (1 + gstPercentage);
            TDSonePercentage = amountExcludingGST * 0.01; 
            
            balanceInterest = interestDelayTillPrevious - interestPaidTillPrevious;
            if (presentDueResult != null && presentDueResult.get('paymentPercentageTill') != null) {
                milestonePaymentPercent = milestonePaymentPercent + (Decimal) presentDueResult.get('paymentPercentageTill');
            }
            if (book.Interest_Waive_Off__c != null) {
                waveOff = book.Interest_Waive_Off__c;
            }
            AggregateResult totalReceied = [
                SELECT SUM(Received_Amount1__c) totalReceivedAmount
                FROM Payment_Schedule__c
                WHERE Booking__c = :book.Id
            ];
            
            if (totalReceied != null && totalReceied.get('totalReceivedAmount') != null) {
                paidTotalAmount = (Decimal) totalReceied.get('totalReceivedAmount');
            }
            if (book.Debit_Amount__c != null){
                paidTotalAmount-= book.Debit_Amount__c;
            }
            paidTillPrevMilestone =  paidTotalAmount;
            balanceDueTillPrevMilestoneMod = totalPayableAmount - paidTotalAmount;
            if(balanceDueTillPrevMilestoneMod > 0){
                balanceDueTillPrevMilestone = totalPayableAmount - paidTotalAmount;
            }
            milestonePaymentPercentTill = milestonePaymentPercent.setScale(0);
            
            double totalAmount = (balanceDueTillPrevMilestoneMod + (interestDelayTillPrevious - interestPaidTillPrevious) + presentDue).setScale(0);
            
            if(totalAmount > -1){
                totalAmountPayable = totalAmount;
            }
            
            NumberTOWordConvertion convert = new NumberTOWordConvertion();
            
            if (totalAmountPayable != null && totalAmountPayable > -1) {
                totalAmountPayableInWords = convert.getNumberTOWordConvertion(totalAmountPayable);
            }
           String fileIdsString = String.join(documentIds, ',');
            
            Demand_Raised__c re = new Demand_Raised__c();
            re.Total_Amount_till_Current_Milestone__C = totalPayableAmount;
            re.Total_Paid_Till__c = paidTotalAmount > 0 ? paidTotalAmount : 0;
            re.Previous_pendings__c = balanceDueTillPrevMilestone;
            re.Interest_Delay_Till_Previous_Milestone__c = totalInterestUplodateAmount;
            re.Total_Interest_Paid__c = totalInterestPaid;
            re.Current_Demand_amount__c = presentDue;
            re.Intrest_Amount__c = balanceInterest;
            re.Grand_Total__c = totalAmountPayable;
            re.Grand_Total_In_Words__c = totalAmountPayableInWords;
            re.Current_Milestone__c = currentCompletedStage;
            re.Milestone_Completed_Date__c = currentCompletedStageDate;
            re.Milestone_Number__c = currentMilestoneNumber;
            re.Due_Date__c = System.Now().addDays(7);
            re.Current_Milestone_Percentage__c = currentMilestonePaymentPercent;
            re.Total_Percentage_till_Current_Milestone__c = milestonePaymentPercentTill;
            re.TDS_Amount__c = TDSonePercentage;
            re.Booking__c = Book.Id;
            re.Total_Flat_Cost__c = Book.Total__c;
            re.Finance_User__c = book.Finance_User__c;
            re.Demand_Email_Content__c = emailContent;
            re.Demand_Content_Ids__c = fileIdsString;
            re.Demanded_Date__c = System.Now();
            re.Payment_schedule__c = scheduleId;
            
            try {
                insert re;
                return 'Demand Raise records created and submitted for approval.';
            } catch (DmlException e) {
                System.debug('Error inserting record: ' + e.getMessage());
                return 'Error: ' + e.getMessage();
            }
        }else{
            return 'ERROR: No milestone records';
        }
    }
    
    public static Map<Integer, String> daySuffixMap = new Map<Integer, String>{1 => 'st', 2 => 'nd', 3 => 'rd', 21 => 'st', 22 => 'nd', 23 => 'rd', 31 => 'st'};
    public static String getMilestoneLabel(Integer sNo) {
        if (sNo == null) {
            return 'Invalid milestone';
        }
        // Determine the suffix, default to 'th'
        String suffix = daySuffixMap.containsKey(sNo) ? daySuffixMap.get(sNo) : 'th';
        
        return sNo + suffix;
    }
}