force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <value>Apartments</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tower</relationshipLabel>
    <relationshipName>Block</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>3 BHK + 2T</fullName>
            </value>
            <value>
                <fullName>4BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
            <value>
                <fullName>B5</fullName>
            </value>
            <value>
                <fullName>B6</fullName>
            </value>
            <value>
                <fullName>B7</fullName>
            </value>
            <value>
                <fullName>B8</fullName>
            </value>
            <value>
                <fullName>B9</fullName>
            </value>
            <value>
                <fullName>B10</fullName>
            </value>
            <value>
                <fullName>B11</fullName>
            </value>
            <value>
                <fullName>B13</fullName>
            </value>
            <value>
                <fullName>B17</fullName>
            </value>
            <value>
                <fullName>B18</fullName>
            </value>
            <value>
                <fullName>B19</fullName>
            </value>
            <value>
                <fullName>B20</fullName>
            </value>
            <value>
                <fullName>B21</fullName>
            </value>
            <value>
                <fullName>B23</fullName>
            </value>
            <value>
                <fullName>B27</fullName>
            </value>
            <value>
                <fullName>B28</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C8</fullName>
            </value>
            <value>
                <fullName>C9</fullName>
            </value>
            <value>
                <fullName>C10</fullName>
            </value>
            <value>
                <fullName>C12</fullName>
            </value>
            <value>
                <fullName>C13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Carpet_Area__c</fullName>
    <label>Carpet Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Facing__c.field-meta.xml
<CustomField>
    <fullName>Facing__c</fullName>
    <label>Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EAST</fullName>
            </value>
            <value>
                <fullName>WEST</fullName>
            </value>
            <value>
                <fullName>SOUTH</fullName>
            </value>
            <value>
                <fullName>NORTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/GST_on_Corpus_Fund__c.field-meta.xml
<CustomField>
    <fullName>GST_on_Corpus_Fund__c</fullName>
    <label>GST % on Corpus Fund</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/GST_on_Maintenance_Charge__c.field-meta.xml
<CustomField>
    <fullName>GST_on_Maintenance_Charge__c</fullName>
    <label>GST % on Maintenance Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Is_Premium_Unit__c.field-meta.xml
<CustomField>
    <fullName>Is_Premium_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>premium unit or not</description>
    <label>Is Premium Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Maintenance_Charge__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Charge__c</fullName>
    <label>Maintenance Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Premium_Charge__c.field-meta.xml
<CustomField>
    <fullName>Premium_Charge__c</fullName>
    <label>Premium Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Price_Per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Sq_Ft__c</fullName>
    <label>Price Per Sq Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Apartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/QA_Given__c.field-meta.xml
<CustomField>
    <fullName>QA_Given__c</fullName>
    <defaultValue>false</defaultValue>
    <description>quality assurance for the unit</description>
    <label>QA Given</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT RELEASE FOR SALE</fullName>
                <label>Not Release For Sale</label>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Super_built_up_area__c.field-meta.xml
<CustomField>
    <fullName>Super_built_up_area__c</fullName>
    <label>Super Built Up Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/EB_Debris_Charges__c.field-meta.xml
<CustomField>
    <fullName>EB_Debris_Charges__c</fullName>
    <label>EB &amp; Debris Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Maintenance_Charge__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Charge__c</fullName>
    <label>Maintenance Charge Per Sq ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_Maintenance_Years__c.field-meta.xml
<CustomField>
    <fullName>No_of_Maintenance_Years__c</fullName>
    <label>No of Maintenance Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Premium_Charge_Per_Sq_ft__c.field-meta.xml
<CustomField>
    <fullName>Premium_Charge_Per_Sq_ft__c</fullName>
    <label>Premium Charge Per Sq ft</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plots</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Apartments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate_Revision_History__c/Rate_Revision_History__c.object-meta.xml
<CustomObject>
    <label>Rate Revision History</label>
    <nameField>
        <displayFormat>URR-{00000}</displayFormat>
        <label>Rate Revision History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_Revision_History__c/fields/Changed_Fields__c.field-meta.xml
<CustomField>
    <fullName>Changed_Fields__c</fullName>
    <label>Changed Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate_Revision_History__c/fields/Changed_Values__c.field-meta.xml
<CustomField>
    <fullName>Changed_Values__c</fullName>
    <label>Changed Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate_Revision_History__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Rate Revision Histories</relationshipLabel>
    <relationshipName>Rate_Revision_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitTriggerTest.cls
@isTest
public class UnitTriggerTest {

    @TestSetup
    static void setupData() {
        Project__c project = new Project__c(
            Name = 'Test Project UT',
            Project_Type__c = 'Apartments',
            Corpus_Fund__c = 50000,
            GST_on_Corpus_Fund__c = 18,
            Maintenance_Charge__c = 5,
            GST_on_Maintenance_Charge__c = 18,
            No_of_Maintenance_Years__c = 10,
            Premium_Charge_Per_Sq_ft__c = 200,
            EB_Debris_Charges__c = 25000
        );
        insert project;

        Plot__c unit = new Plot__c(
            Name = '101',
            Status__c = 'Available',
            Project__c = project.Id,
            Project_Type__c = 'Apartments',
            Block__c = 'A2',
            Plot_Type__c = 'Residential',
            Floor__c = '1',
            Carpet_Area__c = 850,
            Super_built_up_area__c = 1500,
            Price_Per_Sq_Ft__c = 5000,
            BHK_Type__c = '3 BHK + 2T',
            Premium_Status__c = 'Premium',
            Share__c = 'MHPL',
            Facing__c = 'EAST'
        );
        insert unit;
    }

    private static Project__c getProject() {
        return [SELECT Id, Name, Corpus_Fund__c, GST_on_Corpus_Fund__c,
                       Maintenance_Charge__c, GST_on_Maintenance_Charge__c,
                       No_of_Maintenance_Years__c, Premium_Charge_Per_Sq_ft__c
                FROM Project__c LIMIT 1];
    }

    private static Plot__c getPlot() {
        return [SELECT Id, Name, Project__c, Corpus_Fund__c, GST_on_Corpus_Fund__c,
                       Maintenance_Charge__c, GST_on_Maintenance_Charge__c,
                       Premium_Charge__c, Super_built_up_area__c, Price_Per_Sq_Ft__c,
                       Is_Premium_Unit__c, QA_Given__c
                FROM Plot__c LIMIT 1];
    }

    // ── BEFORE INSERT: Auto-generate Name from Floor + Plot_Number ──
    @isTest
    static void testBeforeInsertAutoNameGeneration() {
        Project__c project = getProject();

        Test.startTest();
        Plot__c plot = new Plot__c(
            Project__c = project.Id,
            Project_Type__c = 'Apartments',
            Floor__c = '1',
            Plot_Number__c = '5',
            Status__c = 'Available',
            Block__c = 'A2',
            Plot_Type__c = 'Residential'
        );
        insert plot;
        Test.stopTest();

        Plot__c inserted = [SELECT Name FROM Plot__c WHERE Id = :plot.Id];
        System.assertEquals('105', inserted.Name, 'Name should be auto-generated as Floor + padded PlotNumber');
    }

    // ── BEFORE INSERT: Project field mapping (Corpus, GST, Maintenance) ──
    @isTest
    static void testBeforeInsertProjectFieldMapping() {
        Project__c project = getProject();

        Test.startTest();
        Plot__c plot = new Plot__c(
            Name = 'MapTest',
            Project__c = project.Id,
            Project_Type__c = 'Apartments',
            Status__c = 'Available',
            Block__c = 'A2',
            Plot_Type__c = 'Residential',
            Super_built_up_area__c = 1000
        );
        insert plot;
        Test.stopTest();

        Plot__c inserted = [SELECT Corpus_Fund__c, GST_on_Corpus_Fund__c,
                                   Maintenance_Charge__c, GST_on_Maintenance_Charge__c
                            FROM Plot__c WHERE Id = :plot.Id];
        System.assertEquals(project.Corpus_Fund__c, inserted.Corpus_Fund__c, 'Corpus Fund should map from Project');
        System.assertEquals(project.GST_on_Corpus_Fund__c, inserted.GST_on_Corpus_Fund__c, 'GST on Corpus should map');
        System.assertNotEquals(null, inserted.Maintenance_Charge__c, 'Maintenance Charge should be calculated');
    }

    // ── BEFORE INSERT: Premium Charge calculation ──
    @isTest
    static void testBeforeInsertPremiumChargeCalc() {
        Project__c project = getProject();

        Test.startTest();
        Plot__c plot = new Plot__c(
            Name = 'PremTest',
            Project__c = project.Id,
            Project_Type__c = 'Apartments',
            Status__c = 'Available',
            Block__c = 'A2',
            Plot_Type__c = 'Residential',
            Is_Premium_Unit__c = true,
            Super_built_up_area__c = 1500
        );
        insert plot;
        Test.stopTest();

        Plot__c inserted = [SELECT Premium_Charge__c FROM Plot__c WHERE Id = :plot.Id];
        Decimal expected = project.Premium_Charge_Per_Sq_ft__c * 1500;
        System.assertEquals(expected, inserted.Premium_Charge__c, 'Premium Charge = Per Sqft * Area');
    }

    
    // ── BEFORE UPDATE: Rate Revision History on Price change ──
    @isTest
    static void testBeforeUpdateRateRevisionHistory() {
        Plot__c plot = getPlot();

        Test.startTest();
        plot.Price_Per_Sq_Ft__c = 6000;
        update plot;
        Test.stopTest();

        List<Rate_Revision_History__c> history = [
            SELECT Changed_Fields__c, Changed_Values__c
            FROM Rate_Revision_History__c WHERE Unit__c = :plot.Id
        ];
        System.assert(!history.isEmpty(), 'Rate Revision History should be created on price change');
        System.assert(history[0].Changed_Fields__c.contains('Price Per Sq Ft'),
            'Changed fields should include Price Per Sq Ft');
    }

    // ── BEFORE UPDATE: Name change tracking ──
    @isTest
    static void testBeforeUpdateNameChange() {
        Plot__c plot = getPlot();

        Test.startTest();
        plot.Name = '202';
        update plot;
        Test.stopTest();

        List<Rate_Revision_History__c> history = [
            SELECT Changed_Fields__c FROM Rate_Revision_History__c WHERE Unit__c = :plot.Id
        ];
        System.assert(!history.isEmpty(), 'Rate Revision History should be created on name change');
        System.assert(history[0].Changed_Fields__c.contains('Name'), 'Changed fields should include Name');
    }

    // ── BEFORE UPDATE: Premium recalc when Super_built_up_area changes ──
    @isTest
    static void testBeforeUpdatePremiumRecalcOnAreaChange() {
        Plot__c plot = getPlot();
        Project__c project = getProject();

        Test.startTest();
        plot.Super_built_up_area__c = 2000;
        plot.Is_Premium_Unit__c = true;
        update plot;
        Test.stopTest();

        Plot__c updated = [SELECT Premium_Charge__c, Maintenance_Charge__c FROM Plot__c WHERE Id = :plot.Id];
        Decimal expectedPremium = project.Premium_Charge_Per_Sq_ft__c * 2000;
        System.assertEquals(expectedPremium, updated.Premium_Charge__c,
            'Premium Charge should be recalculated on area change');
        System.assertNotEquals(null, updated.Maintenance_Charge__c,
            'Maintenance Charge should be recalculated');
    }

    // ── BEFORE UPDATE: Is_Premium_Unit toggle off → Premium = 0 ──
    @isTest
    static void testBeforeUpdateIsPremiumToggleOff() {
        Plot__c plot = getPlot();

        // First set to premium
        plot.Is_Premium_Unit__c = true;
        update plot;

        Test.startTest();
        plot.Is_Premium_Unit__c = false;
        update plot;
        Test.stopTest();

        Plot__c updated = [SELECT Premium_Charge__c FROM Plot__c WHERE Id = :plot.Id];
        System.assertEquals(0, updated.Premium_Charge__c, 'Premium Charge should be 0 when not premium');
    }

    // ── AFTER UPDATE: QA_Given__c changes to true (notification) ──
    @isTest
    static void testAfterUpdateQAGiven() {
        Plot__c plot = getPlot();

        Test.startTest();
        plot.QA_Given__c = true;
        update plot;
        Test.stopTest();

        // Notification type may not exist — trigger handles gracefully with try-catch + return
        System.assert(true, 'QA Given update completed without unhandled exception');
    }

    // ── BEFORE UPDATE: No field changes (no Rate Revision History created) ──
    @isTest
    static void testBeforeUpdateNoChanges() {
        Plot__c plot = getPlot();

        Test.startTest();
        // Update with same values — no field changes
        update plot;
        Test.stopTest();

        List<Rate_Revision_History__c> history = [
            SELECT Id FROM Rate_Revision_History__c WHERE Unit__c = :plot.Id
        ];
        System.assertEquals(0, history.size(), 'No history should be created when nothing changed');
    }
}