force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <value>Apartments</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tower</relationshipLabel>
    <relationshipName>Block</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Booking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cost_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Sheet</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Interest_Waive_Off__c.field-meta.xml
<CustomField>
    <fullName>Interest_Waive_Off__c</fullName>
    <label>Interest Waive Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total__c -   Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Property_Type_For__c.field-meta.xml
<CustomField>
    <fullName>Property_Type_For__c</fullName>
    <formula>TEXT(Plot__r.Project__r.Project_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Type For</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Waive_Off__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Waive_Off__c</fullName>
    <label>Total Waive Off Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Plot__r.Block1__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/Master_Payment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Master Payment Schedule</label>
    <nameField>
        <label>Payment Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Master Payment Schedules</relationshipLabel>
    <relationshipName>Master_payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Payment_Schedule__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Master Payment Schedules</relationshipLabel>
    <relationshipName>Master_Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/AmountB__c.field-meta.xml
<CustomField>
    <fullName>AmountB__c</fullName>
    <description>Payment_percent__c *  Booking__r.Total__c</description>
    <formula>Cost_Sheet__r.Grand_Total__c  * Payment_percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Cost_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cost Sheet</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <formula>/*If( Include_Interest__c ,if(Payment_Due_Date__c &lt; TODAY() &amp;&amp;  ISBLANK(Last_Payment_Date__c),
			(Pending_Amount__c *  Interest_Percent__c * (TODAY() - Payment_Due_Date__c))/365 ,
			if(Last_Payment_Date__c &lt; TODAY() &amp;&amp; !ISBLANK(Last_Payment_Date__c),
						(Pending_Amount__c *  Interest_Percent__c * (TODAY() - Last_Payment_Date__c))/365, 0.0)),0)*/

IF(
				Include_Interest__c,
				IF(
								!ISBLANK(Payment_Due_Date__c) &amp;&amp; Payment_Due_Date__c &lt; TODAY(),
								 MAX(((Pending_Amount__c * Interest_Percent__c * (TODAY() - Payment_Due_Date__c)) / 365),0),0),0) 

								/*IF(
												ISBLANK(Payment_Due_Date__c) &amp;&amp; !ISBLANK(Demand_Date__c) &amp;&amp; Demand_Date__c,
												IF(
																!ISBLANK(Interest_Change_Date__c) &amp;&amp; Interest_Change_Date__c &gt; Last_Payment_Date__c,
																(Pending_Amount__c * Interest_Percent__c * (TODAY() - Interest_Change_Date__c)) / 365,
																(Pending_Amount__c * Interest_Percent__c * (TODAY() - Last_Payment_Date__c)) / 365
												),
												0.0
								)
				),
				0
)*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid (From RL)</label>
    <summarizedField>Receipt_Line_Item__c.Received_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Payment_Type__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>/*ABS(Balance_Amount__c -  Received_Amount1__c)*/
 AmountB__c  - Received_Amount1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount1__c</fullName>
    <label>Received Amount through Receipts</label>
    <summarizedField>Receipt_Line_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt_Line_Item__c.Approval_Status__c</field>
        <operation>notEqual</operation>
        <value>Rejected by Finance Team</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt_Line_Item__c.Payment_schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Demanded</fullName>
                <isActive>false</isActive>
                <label>Demanded</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>5</defaultValue>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparation</fullName>
                <default>true</default>
                <label>Preparation</label>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Closed Successfully</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RaiseDemandController.cls
public class RaiseDemandController {
    public Decimal totAmtDueTillPrevMilestone { get; set; }
    public Decimal paidTillPrevMilestone { get; set; }
    public Decimal balanceDueTillPrevMilestone { get; set; }
    public Decimal interestDelayTillPrevious { get; set; }
    public Decimal interestPaidTillPrevious { get; set; }
    public Decimal presentDue { get; set; }
    public Decimal balanceInterest { get; set; }
    public Decimal totalAmountPayable { get; set; }
    public String totalAmountPayableInWords { get; set; }
    public String currentCompletedStage { get; set; }
    public Date currentCompletedStageDate { get; set; }
    public String currentMilestoneNumber { get; set; }
    public Date demandDueDate { get; set; }
    public Decimal currentMilestonePaymentPercent { get; set; }
    public Decimal milestonePaymentPercentTill { get; set; }
    public Decimal TDSonePercentage { get; set; }
    
    // New properties for payment breakup table
    public List<PaymentBreakup> paymentBreakups { get; set; }
    
    public class PaymentBreakup {
        public String scheduleNo { get; set; }
        public String scheduleName { get; set; }
        public Decimal totalAmount { get; set; }
        public Decimal paidAmount { get; set; }
        public Decimal pendingAmount { get; set; }
        public Boolean isCurrent { get; set; }
    }
    
    public static Map<Integer, String> daySuffixMap = new Map<Integer, String>{1 => 'st', 2 => 'nd', 3 => 'rd', 21 => 'st', 22 => 'nd', 23 => 'rd', 31 => 'st'};
        
    public RaiseDemandController(ApexPages.StandardController controller) {
        
        // Initialize payment breakups list
            paymentBreakups = new List<PaymentBreakup>();
            
            totAmtDueTillPrevMilestone =0;
            paidTillPrevMilestone =0;
            balanceDueTillPrevMilestone =0;
            interestDelayTillPrevious =0;
            presentDue =0;
            totalAmountPayable =0;
            TDSonePercentage=0;
            interestPaidTillPrevious =0;
            
            Id bookingRecordId = ApexPages.currentPage().getParameters().get('Id');
            
            if (bookingRecordId == null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Booking record Id is null.'));
                return;
            }
            
            Booking__c book = [SELECT Id,Interest_Waive_Off__c,Total_Interest_Waive_Off__c,GST__c,Debit_Amount__c, Name, Project__c,Project1__r.Name, Property_Type_For__c, Block__c, Tower__c FROM Booking__c WHERE Id = :bookingRecordId];
            
            system.debug('>>>>>>>>>>>>>>>>>'+book.Property_Type_For__c);
            if (book.Property_Type_For__c == 'Apartments') {
                apartmentScheduleCalculations(book);
            }else if (book.Property_Type_For__c == 'Villas')  {
                //villaScheduleCalculations(book);
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No "Property Type" selected for this booking.'));
                return;
            }
        
            
        }
    
    private void apartmentScheduleCalculations(Booking__c book) {
        Booking__c bookRec = [Select id,name,Cost_Sheet__c,Cost_Sheet__r.Payment_Type__c from Booking__c where Id =:book.Id];
        String PaymentType =  bookRec.Cost_Sheet__r.Payment_Type__c;
        
        if(PaymentType == 'Standard'){
            list<Master_Payment_Schedule__c> msRecordList = [
                SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c
                FROM Master_Payment_Schedule__c
                WHERE Status__c = 'Completed' AND Tower__c = :book.Tower__c
                ORDER BY S_No__c DESC LIMIT 1
            ];
            if (msRecordList.isEmpty()) {
                // Handle case where no milestones are completed
                currentCompletedStage = 'No milestone completed';
                currentCompletedStageDate = null;
                demandDueDate = null;
                currentMilestonePaymentPercent = 0;
                currentMilestoneNumber = null;
                totalAmountPayableInWords = 'Zero';
                
                // Optionally, you could log or show a message
                System.debug('No milestone completed for the booking.');
                return;
            }
            
            Master_Payment_Schedule__c msRecord = msRecordList[0]; 
            
            if (msRecord != null) {
                currentCompletedStage = msRecord.Name;
                currentCompletedStageDate = msRecord.Completed_Date__c;
                demandDueDate = System.today().addDays(7);
                currentMilestonePaymentPercent = msRecord.Payment_percent__c != null ? msRecord.Payment_percent__c.setScale(0) : 0;
                
                // Get payment breakups for the table
                getPaymentBreakups(book, msRecord.S_No__c, PaymentType);
                
                Decimal stNumber = msRecord.S_No__c;
                if (stNumber != null) {
                    currentMilestoneNumber = getMilestoneLabel(stNumber.intValue());
                }
                
                AggregateResult[] aggregateResults = [
                    SELECT SUM(Pending_Amount__c) totalPendingAmount, SUM(Interest_Amount__c) totalInterestAmount,
                    SUM(AmountB__c) totalPayableAmount,
                    SUM(Interest_Up_to_Date__c) totalInterestUplodate, SUM(Interest_Paid__c) totalInterestPaid,
                    SUM(Payment_percent__c) paymentPercentageTill
                    FROM Payment_Schedule__c
                    WHERE Master_Payment_Schedule__r.Status__c = 'Completed' 
                    AND Master_Payment_Schedule__r.S_No__c != :msRecord.S_No__c 
                    AND Booking__c = :book.Id
                ];
                
                system.debug('aggregateResults'+aggregateResults);
                Decimal totalPendingAmount = 0;
                Decimal totalInterestAmount = 0;
                Decimal totalPayableAmount = 0;
                Decimal totalReceivedAmount = 0;
                Decimal paidPreMilestone = 0;
                Decimal totalInterestUplodateAmount = 0;
                Decimal totalInterestPaid = 0;
                Decimal waveOff = 0;
                Decimal milestonePaymentPercent = 0;
                Decimal balanceDueTillPrevMilestoneMod = 0;
                Decimal milestonePaymentPercentResult =0;
                if (!aggregateResults.isEmpty()) {
                    totalPendingAmount = (Decimal) aggregateResults[0].get('totalPendingAmount') != null ? (Decimal) aggregateResults[0].get('totalPendingAmount') : 0;
                    totalInterestAmount = (Decimal) aggregateResults[0].get('totalInterestAmount') != null ? (Decimal) aggregateResults[0].get('totalInterestAmount') : 0;
                    totalPayableAmount = (Decimal) aggregateResults[0].get('totalPayableAmount') != null ? (Decimal) aggregateResults[0].get('totalPayableAmount') : 0;
                    totalInterestUplodateAmount = (Decimal) aggregateResults[0].get('totalInterestUplodate') != null ? (Decimal) aggregateResults[0].get('totalInterestUplodate') : 0;
                    totalInterestPaid = (Decimal) aggregateResults[0].get('totalInterestPaid') != null ? (Decimal) aggregateResults[0].get('totalInterestPaid') : 0;
                    milestonePaymentPercent = aggregateResults[0].get('paymentPercentageTill') != null ? (Decimal) aggregateResults[0].get('paymentPercentageTill') : 0;
                }
                system.debug('paidPreMilestone'+paidPreMilestone);
                totAmtDueTillPrevMilestone = totalPayableAmount;
                interestPaidTillPrevious = totalInterestPaid;
                interestDelayTillPrevious = (totalInterestUplodateAmount > 0) ? (totalInterestUplodateAmount) : totalInterestAmount;
                
                double paidTotalAmount = 0;
                AggregateResult presentDueResult = [
                    SELECT SUM(AmountB__c) TotalAmount,SUM(Payment_percent__c) paymentPercentageTill
                    FROM Payment_Schedule__c
                    WHERE Master_Payment_Schedule__r.S_No__c = :msRecord.S_No__c
                    AND Booking__c = :book.Id
                ];
                Decimal presentDueAmount = 0;
                if (presentDueResult != null && presentDueResult.get('TotalAmount') != null) {
                    presentDueAmount = (Decimal) presentDueResult.get('TotalAmount');
                }
                if (presentDueResult != null && presentDueResult.get('paymentPercentageTill') != null) {
                    milestonePaymentPercentResult = milestonePaymentPercent + currentMilestonePaymentPercent;
                }
                
                if (book.Total_Interest_Waive_Off__c != null) {
                    waveOff = book.Total_Interest_Waive_Off__c;
                }
                
                AggregateResult totalReceied = [
                    SELECT SUM(Received_Amount1__c) totalReceivedAmount
                    FROM Payment_Schedule__c
                    WHERE Booking__c = :book.Id
                ];
                
                if (totalReceied != null && totalReceied.get('totalReceivedAmount') != null) {
                    paidTotalAmount = (Decimal) totalReceied.get('totalReceivedAmount');
                }
                if (book.Debit_Amount__c != null){
                    paidTotalAmount-= book.Debit_Amount__c;
                }
                paidTillPrevMilestone =  paidTotalAmount;          
                balanceDueTillPrevMilestoneMod = totalPayableAmount - paidTotalAmount;
                if(balanceDueTillPrevMilestoneMod > 0){
                    balanceDueTillPrevMilestone = totalPayableAmount - paidTotalAmount;
                }
                //milestonePaymentPercentTill = milestonePaymentPercentResult.setScale(0);
                presentDue = presentDueAmount;
                
                Decimal gstPercentage = (book.GST__c != null) ? book.GST__c / 100 : 0;
                Decimal amountExcludingGST = presentDue / (1 + gstPercentage);
                TDSonePercentage = (amountExcludingGST * 0.01).setScale(0);
                
                balanceInterest = interestDelayTillPrevious - interestPaidTillPrevious - waveOff;
                
                double totalAmount = 0;
                totalAmount = (balanceDueTillPrevMilestoneMod + balanceInterest + presentDue).setScale(0);
                
                if(totalAmount > -1){
                    totalAmountPayable = totalAmount;
                }
                
                NumberTOWordConvertion convert = new NumberTOWordConvertion();
                if (totalAmountPayable != null && totalAmountPayable > -1) {
                    totalAmountPayableInWords = convert.getNumberTOWordConvertion(totalAmountPayable);
                }
            }
        }
        else if(PaymentType == 'Custom'){
            
            list<Payment_schedule__c> paysRecordList = [SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c FROM Payment_schedule__c 
                                                        WHERE Status__c = 'Completed' AND Booking__c =: book.Id ORDER BY S_No__c DESC LIMIT 1];
            Payment_schedule__c msRecord = new Payment_schedule__c();
            if(!paysRecordList.isEmpty()){
                msRecord = paysRecordList[0];
            }
            if (msRecord != null) {
                system.debug('in if 192 msRecord');
                currentCompletedStage = msRecord.Name;
                currentCompletedStageDate = msRecord.Completed_Date__c;
                demandDueDate = System.today().addDays(7);
                currentMilestonePaymentPercent = msRecord.Payment_percent__c != null ? msRecord.Payment_percent__c.setScale(0) : 0;
                
                // Get payment breakups for the table
                getPaymentBreakups(book, msRecord.S_No__c, PaymentType);
                
                Decimal stNumber = msRecord.S_No__c;
                if (stNumber != null) {
                    currentMilestoneNumber = getMilestoneLabel(stNumber.intValue());
                }
                
                AggregateResult[] aggregateResults = [
                    SELECT SUM(Pending_Amount__c) totalPendingAmount, SUM(Interest_Amount__c) totalInterestAmount,
                    SUM(AmountB__c) totalPayableAmount,
                    SUM(Interest_Up_to_Date__c) totalInterestUplodate, SUM(Interest_Paid__c) totalInterestPaid,
                    SUM(Payment_percent__c) paymentPercentageTill
                    FROM Payment_Schedule__c
                    WHERE Status__c = 'Completed' 
                    AND S_No__c != :msRecord.S_No__c 
                    AND Booking__c = :book.Id
                ];
                
                system.debug('aggregateResults'+aggregateResults);
                Decimal totalPendingAmount = 0;
                Decimal totalInterestAmount = 0;
                Decimal totalPayableAmount = 0;
                Decimal totalReceivedAmount = 0;
                Decimal paidPreMilestone = 0;
                Decimal totalInterestUplodateAmount = 0;
                Decimal totalInterestPaid = 0;
                Decimal waveOff = 0;
                Decimal milestonePaymentPercent = 0;
                Decimal balanceDueTillPrevMilestoneMod = 0;
                Decimal milestonePaymentPercentResult =0;
                if (!aggregateResults.isEmpty()) {
                    totalPendingAmount = (Decimal) aggregateResults[0].get('totalPendingAmount') != null ? (Decimal) aggregateResults[0].get('totalPendingAmount') : 0;
                    totalInterestAmount = (Decimal) aggregateResults[0].get('totalInterestAmount') != null ? (Decimal) aggregateResults[0].get('totalInterestAmount') : 0;
                    totalPayableAmount = (Decimal) aggregateResults[0].get('totalPayableAmount') != null ? (Decimal) aggregateResults[0].get('totalPayableAmount') : 0;
                    totalInterestUplodateAmount = (Decimal) aggregateResults[0].get('totalInterestUplodate') != null ? (Decimal) aggregateResults[0].get('totalInterestUplodate') : 0;
                    totalInterestPaid = (Decimal) aggregateResults[0].get('totalInterestPaid') != null ? (Decimal) aggregateResults[0].get('totalInterestPaid') : 0;
                    milestonePaymentPercent = aggregateResults[0].get('paymentPercentageTill') != null ? (Decimal) aggregateResults[0].get('paymentPercentageTill') : 0;
                }
                
                system.debug('paidPreMilestone'+paidPreMilestone);
                totAmtDueTillPrevMilestone = totalPayableAmount;
                interestPaidTillPrevious = totalInterestPaid;
                interestDelayTillPrevious = (totalInterestUplodateAmount > 0) ? (totalInterestUplodateAmount) : totalInterestAmount;
                
                double paidTotalAmount = 0;
                AggregateResult presentDueResult = [
                    SELECT SUM(AmountB__c) TotalAmount,SUM(Payment_percent__c) paymentPercentageTill
                    FROM Payment_Schedule__c
                    WHERE S_No__c = :msRecord.S_No__c
                    AND Booking__c = :book.Id
                ];
                Decimal presentDueAmount = 0;
                if (presentDueResult != null && presentDueResult.get('TotalAmount') != null) {
                    presentDueAmount = (Decimal) presentDueResult.get('TotalAmount');
                }
                if (presentDueResult != null && presentDueResult.get('paymentPercentageTill') != null) {
                    milestonePaymentPercentResult = milestonePaymentPercent + currentMilestonePaymentPercent;
                }
                
                if (book.Total_Interest_Waive_Off__c != null) {
                    waveOff = book.Total_Interest_Waive_Off__c;
                }
                
                AggregateResult totalReceied = [
                    SELECT SUM(Received_Amount1__c) totalReceivedAmount
                    FROM Payment_Schedule__c
                    WHERE Booking__c = :book.Id
                ];
                
                if (totalReceied != null && totalReceied.get('totalReceivedAmount') != null) {
                    paidTotalAmount = (Decimal) totalReceied.get('totalReceivedAmount');
                }
                if (book.Debit_Amount__c != null){
                    paidTotalAmount-= book.Debit_Amount__c;
                }
                paidTillPrevMilestone =  paidTotalAmount;          
                balanceDueTillPrevMilestoneMod = totalPayableAmount - paidTotalAmount;
                if(balanceDueTillPrevMilestoneMod > 0){
                    balanceDueTillPrevMilestone = totalPayableAmount - paidTotalAmount;
                }
                //milestonePaymentPercentTill = milestonePaymentPercentResult.setScale(0);
                presentDue = presentDueAmount;
                
                Decimal gstPercentage = (book.GST__c != null) ? book.GST__c / 100 : 0;
                Decimal amountExcludingGST = presentDue / (1 + gstPercentage);
                TDSonePercentage = (amountExcludingGST * 0.01).setScale(0);
                
                balanceInterest = interestDelayTillPrevious - interestPaidTillPrevious - waveOff;
                
                double totalAmount = 0;
                totalAmount = (balanceDueTillPrevMilestoneMod + balanceInterest + presentDue).setScale(0);
                
                if(totalAmount > -1){
                    totalAmountPayable = totalAmount;
                }
                
                NumberTOWordConvertion convert = new NumberTOWordConvertion();
                if (totalAmountPayable != null && totalAmountPayable > -1) {
                    totalAmountPayableInWords = convert.getNumberTOWordConvertion(totalAmountPayable);
                }
            }
        }
        
    }
    
     private void getPaymentBreakups(Booking__c book, Decimal currentMilestoneSNo, String paymentType) {
        paymentBreakups = new List<PaymentBreakup>();
        
        List<Payment_Schedule__c> schedules = new List<Payment_Schedule__c>();
        
        if(paymentType == 'Standard') {
            schedules = [
                SELECT Id, Name, S_No__c, AmountB__c, Received_Amount1__c, Pending_Amount__c, 
                       Master_Payment_Schedule__r.Name,Master_Payment_Schedule__r.S_No__c,Master_Payment_Schedule__r.Status__c
                FROM Payment_Schedule__c
                WHERE Booking__c = :book.Id
                AND (Master_Payment_Schedule__r.Status__c = 'Completed' OR Master_Payment_Schedule__r.S_No__c = :currentMilestoneSNo)
                ORDER BY Master_Payment_Schedule__r.S_No__c
            ];
        } else if(paymentType == 'Custom') {
            schedules = [
                SELECT Id, Name, S_No__c, AmountB__c, Received_Amount1__c, Pending_Amount__c, Status__c
                FROM Payment_Schedule__c
                WHERE Booking__c = :book.Id
                AND (Status__c = 'Completed' OR S_No__c = :currentMilestoneSNo)
                ORDER BY S_No__c
            ];
        }
        
        for(Payment_Schedule__c schedule : schedules) {
            PaymentBreakup breakup = new PaymentBreakup();
            
            if(paymentType == 'Standard') {
                breakup.scheduleNo = String.valueOf(schedule.Master_Payment_Schedule__r.S_No__c);
                breakup.scheduleName = schedule.Master_Payment_Schedule__r.Name;
            } else {
                breakup.scheduleNo = String.valueOf(schedule.S_No__c);
                breakup.scheduleName = schedule.Name;
            }
            
            breakup.totalAmount = schedule.AmountB__c != null ? schedule.AmountB__c : 0;
            breakup.paidAmount = schedule.Received_Amount1__c != null ? schedule.Received_Amount1__c : 0;
            breakup.pendingAmount = schedule.Pending_Amount__c != null ? schedule.Pending_Amount__c : 0;
            breakup.isCurrent = (paymentType == 'Standard' ? 
                                schedule.Master_Payment_Schedule__r.S_No__c == currentMilestoneSNo : 
                                schedule.S_No__c == currentMilestoneSNo);
            
            paymentBreakups.add(breakup);
        }
    }
    
    /*private void villaScheduleCalculations(Booking__c book) {
List<Payment_Schedule__c> psRecordList = [
SELECT Id, Name, S_No__c, Completed_Date__c, Payment_percent__c
FROM Payment_Schedule__c
WHERE Status__c = 'Completed' AND Booking__c = :book.Id
ORDER BY S_No__c DESC LIMIT 1
];
if (psRecordList.isEmpty()) {
// Handle case where no milestones are completed
currentCompletedStage = 'No milestone completed';
currentCompletedStageDate = null;
demandDueDate = null;
currentMilestonePaymentPercent = 0;
currentMilestoneNumber = null;
totalAmountPayableInWords = 'Zero';

// Optionally, you could log or show a message
System.debug('No milestone completed for the booking.');
return;
}

Payment_Schedule__c psRecord = psRecordList[0]; 

if (psRecord != null) {
currentCompletedStage = psRecord.Name;
currentCompletedStageDate = psRecord.Completed_Date__c;
demandDueDate = System.today().addDays(7);
currentMilestonePaymentPercent = psRecord.Payment_percent__c != null ? psRecord.Payment_percent__c.setScale(0) : 0;

Decimal stNumber = psRecord.S_No__c;
if (stNumber != null) {
currentMilestoneNumber = getMilestoneLabel(stNumber.intValue());
}

AggregateResult[] aggregateResults = [
SELECT SUM(Pending_Amount__c) totalPendingAmount, 
SUM(Interest_Amount__c) totalInterestAmount,
SUM(AmountB__c) totalPayableAmount,
SUM(Interest_Up_to_Date__c) totalInterestUplodate, 
SUM(Interest_Paid__c) totalInterestPaid,
SUM(Payment_percent__c) paymentPercentageTill
FROM Payment_Schedule__c
WHERE Status__c = 'Completed' 
AND S_No__c != :psRecord.S_No__c 
AND Booking__c = :book.Id
];

Decimal totalPendingAmount = 0;
Decimal totalInterestAmount = 0;
Decimal totalPayableAmount = 0;
Decimal paidPreMilestone = 0;
Decimal totalInterestUplodateAmount = 0;
Decimal totalInterestPaid = 0;
Decimal waveOff = 0;
Decimal milestonePaymentPercent =0;
Decimal balanceDueTillPrevMilestoneMod = 0;
if (!aggregateResults.isEmpty()) {
totalPendingAmount = (Decimal) aggregateResults[0].get('totalPendingAmount') != null ? (Decimal) aggregateResults[0].get('totalPendingAmount') : 0;
totalInterestAmount = (Decimal) aggregateResults[0].get('totalInterestAmount') != null ? (Decimal) aggregateResults[0].get('totalInterestAmount') : 0;
totalPayableAmount = (Decimal) aggregateResults[0].get('totalPayableAmount') != null ? (Decimal) aggregateResults[0].get('totalPayableAmount') : 0;
totalInterestUplodateAmount = (Decimal) aggregateResults[0].get('totalInterestUplodate') != null ? (Decimal) aggregateResults[0].get('totalInterestUplodate') : 0;
totalInterestPaid = (Decimal) aggregateResults[0].get('totalInterestPaid') != null ? (Decimal) aggregateResults[0].get('totalInterestPaid') : 0;
milestonePaymentPercent = (Decimal) aggregateResults[0].get('paymentPercentageTill') != null ? (Decimal) aggregateResults[0].get('paymentPercentageTill') : 0;
}

totAmtDueTillPrevMilestone = totalPayableAmount;
interestPaidTillPrevious = totalInterestPaid;
interestDelayTillPrevious = (totalInterestUplodateAmount > 0) ? (totalInterestUplodateAmount) : totalInterestAmount;

double paidTotalAmount = 0;
AggregateResult presentDueResult = [
SELECT SUM(AmountB__c) totalAmountB,
SUM(Payment_percent__c) paymentPercentageTill
FROM Payment_Schedule__c
WHERE S_No__c = :psRecord.S_No__c
AND Booking__c = :book.Id
];

Decimal presentDueAmount = 0;
if (presentDueResult != null && presentDueResult.get('totalAmountB') != null) {
presentDueAmount = (Decimal) presentDueResult.get('totalAmountB');
}
presentDue = presentDueAmount;

Decimal gstPercentage = (book.GST__c != null) ? book.GST__c / 100 : 0;
Decimal amountExcludingGST = presentDue / (1 + gstPercentage);
Decimal TDSonePercentage = amountExcludingGST * 0.01; 

balanceInterest = interestDelayTillPrevious - interestPaidTillPrevious;
if (presentDueResult != null && presentDueResult.get('paymentPercentageTill') != null) {
milestonePaymentPercent = milestonePaymentPercent + (Decimal) presentDueResult.get('paymentPercentageTill');
}
if (book.Total_Interest_Waive_Off__c != null) {
waveOff = book.Total_Interest_Waive_Off__c;
}
AggregateResult totalReceied = [
SELECT SUM(Received_Amount1__c) totalReceivedAmount
FROM Payment_Schedule__c
WHERE Booking__c = :book.Id
];

if (totalReceied != null && totalReceied.get('totalReceivedAmount') != null) {
paidTotalAmount = (Decimal) totalReceied.get('totalReceivedAmount');
}
if (book.Debit_Amount__c != null){
paidTotalAmount-= book.Debit_Amount__c;
}

paidTillPrevMilestone =  paidTotalAmount;          
balanceDueTillPrevMilestoneMod = totalPayableAmount - paidTotalAmount;
if(balanceDueTillPrevMilestoneMod > 0){
balanceDueTillPrevMilestone = totalPayableAmount - paidTotalAmount;
}
milestonePaymentPercentTill = milestonePaymentPercent.setScale(0);

double totalAmount = (balanceDueTillPrevMilestoneMod + (interestDelayTillPrevious - waveOff -  interestPaidTillPrevious) + presentDue).setScale(0);

if(totalAmount > -1){
totalAmountPayable = totalAmount;
}

NumberTOWordConvertion convert = new NumberTOWordConvertion();

if (totalAmountPayable != null && totalAmountPayable > -1) {
totalAmountPayableInWords = convert.getNumberTOWordConvertion(totalAmountPayable);
}
}
}*/
    public static String getMilestoneLabel(Integer sNo) {
        if (sNo == null) {
            return 'Invalid milestone';
        }
        // Determine the suffix, default to 'th'
        String suffix = daySuffixMap.containsKey(sNo) ? daySuffixMap.get(sNo) : 'th';
        
        return sNo + suffix;
    }
}