force-app/main/default/objects/Advance_Payment__c/Advance_Payment__c.object-meta.xml
<CustomObject>
    <label>Advance Payment</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Advance Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advance Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance_Payment__c/fields/Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>Booking_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Request</label>
    <referenceTo>Booking_Request__c</referenceTo>
    <relationshipLabel>Advance Payments</relationshipLabel>
    <relationshipName>Advance_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advance_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <value>Apartments</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tower</relationshipLabel>
    <relationshipName>Block</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/Booking_Request__c.object-meta.xml
<CustomObject>
    <label>Booking Request</label>
    <nameField>
        <displayFormat>BR-{00000}</displayFormat>
        <label>Booking Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Request__c/fields/Blocked_Price__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Price__c</fullName>
    <label>Blocked Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/IsResponded__c.field-meta.xml
<CustomField>
    <fullName>IsResponded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsResponded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Unit__r.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for Response</fullName>
                <default>true</default>
                <label>Waiting for Response</label>
            </value>
            <value>
                <fullName>Cost Sheet Preparation</fullName>
            </value>
            <value>
                <fullName>Request Abandoned</fullName>
            </value>
            <value>
                <fullName>Request Successfully Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Plot__c</referenceTo>
    <relationshipLabel>Booking Requests</relationshipLabel>
    <relationshipName>Booking_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot__c/fields/Basic_Sale_Price_Rs__c.field-meta.xml
<CustomField>
    <fullName>Basic_Sale_Price_Rs__c</fullName>
    <formula>Basic_Price1__c + Covered_Park_Parking__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Basic Sale Price (Rs.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/BHK_Type__c.field-meta.xml
<CustomField>
    <fullName>BHK_Type__c</fullName>
    <label>BHK Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>3 BHK + 2T</fullName>
            </value>
            <value>
                <fullName>4BHK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Block1__c.field-meta.xml
<CustomField>
    <fullName>Block1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Block__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Facing__c.field-meta.xml
<CustomField>
    <fullName>Facing__c</fullName>
    <label>Facing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EAST</fullName>
            </value>
            <value>
                <fullName>WEST</fullName>
            </value>
            <value>
                <fullName>SOUTH</fullName>
            </value>
            <value>
                <fullName>NORTH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Is_PSA_Unit__c.field-meta.xml
<CustomField>
    <fullName>Is_PSA_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PSA Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Price_Per_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Sq_Ft__c</fullName>
    <label>Price Per Sq Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Project_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Plots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to capture the availability of the plot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT RELEASE FOR SALE</fullName>
                <label>Not Release For Sale</label>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot__c/fields/Super_built_up_area__c.field-meta.xml
<CustomField>
    <fullName>Super_built_up_area__c</fullName>
    <label>Super Built Up Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Cost Sheet</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Cost Sheet No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Booking_Request__c.field-meta.xml
<CustomField>
    <fullName>Booking_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Request</label>
    <referenceTo>Booking_Request__c</referenceTo>
    <relationshipLabel>Cost Sheets</relationshipLabel>
    <relationshipName>Cost_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Email_Sent_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent_Date_Time__c</fullName>
    <label>Email Sent Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparation</fullName>
                <default>true</default>
                <label>Preparation</label>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Closed Successfully</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingRequest_Controller.cls
public without sharing class BookingRequest_Controller {
    @AuraEnabled
    public static string send_Booking_Request(string recordId, string EmailId, Integer BlockedPrice){
        
        try{
            Booking_Request__c bk = new Booking_Request__c();
            bk.Unit__c = recordId;
            bk.Email__c = EmailId;
            bk.Blocked_Price__c = BlockedPrice;
            bk.Email_Sent_Date_Time__c = system.now();
            insert bk;
            
            Plot__c pt = [select id,Status__c from Plot__c where id =:recordId];
            pt.Status__c = 'Blocked';
            update pt;
            
            list<Messaging.SingleEmailMessage> message= new  list<Messaging.SingleEmailMessage>();
            
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            string urlval = label.Org_url;
            system.debug(urlval);
            Site mySite = [SELECT Id, Name, Subdomain, UrlPathPrefix FROM Site WHERE Name = 'Booking_Request_Site' LIMIT 1];
            system.debug(mySite.UrlPathPrefix);
            
            /*string  htmlBody='Dear Customer,<br/><br/>Thank you for choosing Jain Housing. We have attached a Hyperlink to fill and submit a booking request. <br/>To Open the Booking requisition page, please click on the link below. <br/>'+
                '<a href="'+urlval+'/'+ mySite.UrlPathPrefix +'?Id='+recordId+'&BkReqId='+bk.Id+'">Click here to request for Booking</a><br/>'+
                'We pride ourselves on providing high-quality Constructions, and we are confident that you will be completely satisfied with the results.<br/> If you have any questions or concerns, please don\'t hesitate to contact us. We are always happy to help.<br/><br/>'+'Thank you<br/>Jain Housing';*/
            String htmlBody = 'Dear Customer,<br/><br/>' +
                'Thank you for choosing Jain Housing to purchase your dream home. We are truly delighted to be part of this important milestone in your life.<br/><br/>' +
                'With over three decades of trusted experience in South India, Jain Housing is committed to delivering quality homes and exceptional service. It is our privilege to assist you on this exciting journey.<br/><br/>' +
                'To continue with the booking, please click the link below to fill in your basic details and make the booking advance:<br/><br/>' +
                '<a href="' + urlval + '/' + mySite.UrlPathPrefix + '?Id=' + recordId + '&BkReqId=' + bk.Id + '">Click here to proceed with the booking</a><br/><br/>' +
                'If you have any questions or need assistance, feel free to reach out to our Sales Team.<br/><br/>' +
                'Warm regards,<br/>' +
                'Sales Team<br/>' +
                '<strong>Team Jain Housing</strong>';

            string email = EmailId;
            //semail.setSubject('Jain Housing\'s Booking Request Page');
            semail.setSubject('Welcome to Jain Housing – Let\'s Get Started on Your Dream Home!');
            semail.setToAddresses(new String[]{email});
            semail.setHtmlBody(htmlBody);
            message.add(semail);  
            Messaging.sendEmail(message);
                        
            return 'Success';
        }
        catch(exception e){
            System.debug('Error while sending booking request email: ' + e.getMessage());
            return 'Error: ' + e.getMessage();
        }
        
        
    }
    
    
    public class UnitWrapper{
        @AuraEnabled 
        public Plot__c UnitRec {get; set;}
        @AuraEnabled 
        public Boolean IsFormResponded {get; set;}
        @AuraEnabled 
        public String BkrqStatus {get; set;}
    }
    
    @AuraEnabled
    public static UnitWrapper GetUnitDetails(string recordId, string BkreqId){
        UnitWrapper utwrp = new UnitWrapper();
        Booking_Request__c bkrq = [select id,IsResponded__c,Stage__c from Booking_Request__c where Id =: BkreqId limit 1];
        Plot__c pt = [select id,name,Plot_Number__c,Project__c,Project__r.Name,Status__c,Block1__c,Block1__r.Name,BHK_Type__c,Floor__c,Facing__c,Is_PSA_Unit__c,Super_built_up_area__c,Price_Per_Sq_Ft__c,Basic_Sale_Price_Rs__c,Total__c from Plot__c where id =: recordId];
        
        if(pt != null)
            utwrp.UnitRec = pt;
        if(bkrq != null){
            utwrp.IsFormResponded = bkrq.IsResponded__c;
            utwrp.BkrqStatus = bkrq.Stage__c;
        }
        return  utwrp;
    }
    
    @AuraEnabled
    public static Boolean check_IsPSA(string recordId){
        string UnitName = [select id,name from Plot__c where Id =: recordId limit 1].Name;
        return UnitName != null && UnitName.containsIgnoreCase('PSA');
    }
    
    @AuraEnabled
    public static Boolean check_EmailExists(string recordId){
        Booking_Request__c brq = [select id,IsResponded__c,Unit__c,Email__c,Email_Sent_Date_Time__c from Booking_Request__c where Id =: recordId limit 1];
        brq.Email_Sent_Date_Time__c = system.now();
        update brq;
        
        string CusEmail = brq.Email__c;
        system.debug(CusEmail);
        if(CusEmail == null || CusEmail == ''){
            return false;
        }
        if(!brq.IsResponded__c){
            list<Messaging.SingleEmailMessage> message= new  list<Messaging.SingleEmailMessage>();
            
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            string urlval = label.Org_url;
            Site mySite = [SELECT Id, Name, Subdomain, UrlPathPrefix FROM Site WHERE Name = 'Booking_Request_Site' LIMIT 1];
            string  htmlBody='Dear Customer,<br/><br/>Thank you for choosing Jain Housing. We have attached a Hyperlink to fill and submit a booking request. <br/>To Open the Booking requisition page, please click on the link below. <br/>'+
                '<a href="'+urlval+'/'+ mySite.UrlPathPrefix +'?Id='+brq.Unit__c+'&BkReqId='+brq.Id+'">Click here to request for Booking</a><br/>'+
                'We pride ourselves on providing high-quality Constructions, and we are confident that you will be completely satisfied with the results.<br/> If you have any questions or concerns, please don\'t hesitate to contact us. We are always happy to help.<br/><br/>'+'Thank you<br/>Jain Housing';
            semail.setSubject('Jain Housing\'s Booking Request Page');
            semail.setToAddresses(new String[]{CusEmail});
            semail.setHtmlBody(htmlBody);
            message.add(semail);  
            Messaging.sendEmail(message);
        }
        return true;
    }
    
    @AuraEnabled
    public static Id createAdvancePayment(Advance_Payment__c payment) {
        insert payment;
        return payment.Id;
    }
    
    @AuraEnabled
    public static Map<String, List<String>> getPicklistValues() {
        Map<String, List<String>> picklistValues = new Map<String, List<String>>();
        
        // Get Payment Mode picklist values
        List<String> paymentModes = new List<String>();
        Schema.DescribeFieldResult paymentModeField = Advance_Payment__c.Mode_of_Payment__c.getDescribe();
        for (Schema.PicklistEntry entry : paymentModeField.getPicklistValues()) {
            paymentModes.add(entry.getValue());
        }
        picklistValues.put('paymentModes', paymentModes);
        
        // Get Bank picklist values
        List<String> banks = new List<String>();
        Schema.DescribeFieldResult bankField = Advance_Payment__c.Bank__c.getDescribe();
        for (Schema.PicklistEntry entry : bankField.getPicklistValues()) {
            banks.add(entry.getValue());
        }
        picklistValues.put('banks', banks);
        
        return picklistValues;
    }
    
    @AuraEnabled
    public static void InsertBookingReq(Booking_Request__c BookingReqt, Advance_Payment__c payment){
        
        system.debug('BookingReqt >> '+ BookingReqt);
        system.debug('payment >> '+ payment);
        
        BookingReqt.Customer_Responded_Date__c = system.now();
        upsert BookingReqt;
        upsert payment;
        
        Booking_Request__c rec = [select id,ownerid,name from Booking_Request__c where id =: BookingReqt.id];
        CustomNotificationType ResponseNotify;
        ResponseNotify = [SELECT Id,DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'Booking_Request_Responded_Notify' LIMIT 1];
                
        Messaging.CustomNotification Notification = new Messaging.CustomNotification();
        Notification.setTitle('Booking Request Update'); 
        Notification.setBody('Booking request ' + rec.Name + ' has been submitted.'); 
        Notification.setNotificationTypeId(ResponseNotify.id); 
        Notification.setSenderId(Userinfo.getUserId()); 
        Notification.setTargetId(BookingReqt.Id); 
        Notification.send(new Set<String>{ rec.OwnerId });
        
        
        /*
        Booking_Request__c bkr = new Booking_Request__c();
        bkr.Customer_Comments__c = BookingReqt.Customer_Comments__c;
        bkr.Customer_Name__c = BookingReqt.Customer_Name__c;
        bkr.Unit__c = BookingReqt.Unit__c;
        bkr.Mobile__c = BookingReqt.Mobile__c;
        bkr.Aadhaar_Number__c = BookingReqt.Aadhaar_Number__c;
        bkr.PAN_Number__c = BookingReqt.PAN_Number__c;
        insert bkr;*/
    }
    
    public static void cancelPendingAdvanceApprovals(Set<Id> bookingRequestIds) {
        // Fetch advance payments linked to those booking requests
        List<Advance_Payment__c> advancePayments = [SELECT Id FROM Advance_Payment__c WHERE Booking_Request__c IN :bookingRequestIds];

        if (advancePayments.isEmpty()) return;

        // Fetch process instances (approval processes) for these advance payments
        List<ProcessInstance> processInstances = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE TargetObjectId IN :advancePayments AND Status = 'Pending'];
 
        if (processInstances.isEmpty()) return;

        // Fetch the work items (steps) of those approval processes
        List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId, ActorId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId IN :processInstances];

        // Cancel each approval request by removing the step
        for (ProcessInstanceWorkitem item : workItems) {
            Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
            pwr.setAction('Reject'); // Rejects the approval step
            pwr.setWorkitemId(item.Id);
            pwr.setComments('Rejected as Booking was created'); // Adds the comment
            Approval.ProcessResult result = Approval.process(pwr);
        }
    }
    
	 
    @AuraEnabled
    public static AbandonResult abandonBookingRequest(String bookingRequestId) {
        AbandonResult result = new AbandonResult();
        result.isSuccess = false;
        Set<Id> bookingRequestIds = new Set<Id>{bookingRequestId};
        
        try {
            // Check if user has permission to update records
            if (!Schema.sObjectType.Booking_Request__c.isUpdateable() || 
                !Schema.sObjectType.Quote__c.isUpdateable()) {
                result.errorMessage = 'You do not have permission to update records.';
                return result;
            }
            
            // Query the booking request first
            Booking_Request__c br = [
                SELECT Id, Stage__c ,Request_Abandoned_Date__c
                FROM Booking_Request__c 
                WHERE Id = :bookingRequestId 
                LIMIT 1
            ];
            
            // Then query related cost sheets (quotes)
            List<Quote__c> relatedQuotes = new List<Quote__c>();
            
            if (Schema.sObjectType.Quote__c.fields.Booking_Request__c.isAccessible()) {
                relatedQuotes = [
                    SELECT Id, Status__c,Cost_Sheet_Abandoned_Date__c 
                    FROM Quote__c 
                    WHERE Booking_Request__c IN :bookingRequestIds
                ];
            }
            
            // Update booking request stage
            br.Stage__c = 'Request Abandoned';
            br.Request_Abandoned_Date__c = system.now();
            
            // Prepare quotes to update
            List<Quote__c> quotesToUpdate = new List<Quote__c>();
            for (Quote__c quote : relatedQuotes) {
                quote.Status__c = 'Abandoned';
                quote.Cost_Sheet_Abandoned_Date__c = system.now();
                quotesToUpdate.add(quote);
            }
            
            // Start transaction
            Savepoint sp = Database.setSavepoint();
            
            try {
                // Update booking request
                update br;
                
                // Update related quotes if they exist
                if (!quotesToUpdate.isEmpty()) {
                    update quotesToUpdate;
                }
                
                // Cancel any pending approval processes for these quotes
                if (!relatedQuotes.isEmpty()) {
                    cancelPendingApprovals(relatedQuotes, 'Cancelled due to abandonment of booking request');
                }
                
                result.isSuccess = true;
            } catch (Exception e) {
                // Rollback on error
                Database.rollback(sp);
                result.errorMessage = 'Error updating records: ' + e.getMessage();
            }
            
        } catch (Exception e) {
            result.errorMessage = 'Error: ' + e.getMessage();
        }
        
        return result;
    }
    
    // Reusable method to cancel pending approvals (based on your reference code)
    private static void cancelPendingApprovals(List<Quote__c> quotes, String comment) {
        Set<Id> quoteIds = new Set<Id>();
        for (Quote__c quote : quotes) {
            quoteIds.add(quote.Id);
        }
        
        // Fetch process instances (approval processes) for these quotes
        List<ProcessInstance> processInstances = [
            SELECT Id, TargetObjectId 
            FROM ProcessInstance 
            WHERE TargetObjectId IN :quoteIds AND Status = 'Pending'
        ];
 
        if (processInstances.isEmpty()) return;

        // Fetch the work items (steps) of those approval processes
        List<ProcessInstanceWorkitem> workItems = [
            SELECT Id, ProcessInstanceId, ActorId 
            FROM ProcessInstanceWorkitem 
            WHERE ProcessInstanceId IN :processInstances
        ];

        // Cancel each approval request by removing the step
        List<Approval.ProcessWorkitemRequest> approvalRequests = new List<Approval.ProcessWorkitemRequest>();
        for (ProcessInstanceWorkitem item : workItems) {
            Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
            pwr.setAction('Removed'); // Removes the approval step
            pwr.setWorkitemId(item.Id);
            pwr.setComments(comment);
            approvalRequests.add(pwr);
        }
        
        if (!approvalRequests.isEmpty()) {
            try {
                List<Approval.ProcessResult> results = Approval.process(approvalRequests);
            } catch (Exception e) {
                System.debug('Error cancelling approvals: ' + e.getMessage());
            }
        }
    }
    
    public class AbandonResult {
        @AuraEnabled public Boolean isSuccess {get; set;}
        @AuraEnabled public String errorMessage {get; set;}
    }
    
}